// apps/frontend/app/src/lib/components/system/collapsible-section.svelte
<script lang="ts">
  import { untrack } from 'svelte';
  import type { Snippet } from 'svelte';
  import { ChevronRight } from 'lucide-svelte';

  interface Props {
    title: string;
    count?: number;
    defaultOpen?: boolean;
    children: Snippet;
  }

  let { title, count, defaultOpen = false, children }: Props = $props();

  let isOpen = $state(untrack(() => defaultOpen));
</script>

<div class="border border-border rounded-lg overflow-hidden">
  <button
    onclick={() => isOpen = !isOpen}
    class="w-full flex items-center gap-2 px-3 py-2 bg-surface-2 hover:bg-surface-2/80 text-left"
  >
    <ChevronRight class="w-4 h-4 text-text-tertiary transition-transform {isOpen ? 'rotate-90' : ''}" />
    <span class="text-sm font-medium text-text-primary">{title}</span>
    {#if count !== undefined}
      <span class="px-1.5 py-0.5 rounded text-2xs bg-surface-1 text-text-secondary">{count}</span>
    {/if}
  </button>
  {#if isOpen}
    <div class="p-3 bg-surface-1">
      {@render children()}
    </div>
  {/if}
</div>

// apps/frontend/concord-app/src/app/components/system/collapsible-section.tsx
import { useState, type ReactNode } from 'react';
import { ChevronRight } from 'lucide-react';

interface CollapsibleSectionProps {
  title: string;
  count?: number;
  defaultOpen?: boolean;
  children: ReactNode;
}

export function CollapsibleSection({ title, count, defaultOpen = false, children }: CollapsibleSectionProps) {
  const [open, setOpen] = useState(defaultOpen);

  return (
    <div className="mb-4">
      <button
        onClick={() => setOpen(!open)}
        className="flex w-full items-center gap-2 rounded-lg border border-border bg-surface-2 px-3 py-2 text-left transition-colors hover:bg-surface-2/80"
      >
        <ChevronRight
          size={14}
          className={`text-text-tertiary transition-transform ${open ? 'rotate-90' : ''}`}
        />
        <span className="text-sm font-medium text-text-primary">{title}</span>
        {count !== undefined && (
          <span className="rounded bg-surface-1 px-1.5 py-0.5 text-2xs text-text-tertiary">
            {count}
          </span>
        )}
      </button>
      {open && <div className="mt-2">{children}</div>}
    </div>
  );
}
