// research/embedded/concord/apps/frontend/app/src/lib/components/system/metric-card.svelte
<script lang="ts">
  import type { Component } from 'svelte';

  type StatusType = 'success' | 'warning' | 'error' | 'info' | 'neutral';

  interface Props {
    label: string;
    value: string | number;
    icon?: Component;
    subtitle?: string;
    status?: StatusType;
  }

  let { label, value, icon, subtitle, status = 'neutral' }: Props = $props();

  const valueColor = $derived.by(() => {
    switch (status) {
      case 'success': return 'text-success';
      case 'warning': return 'text-warning';
      case 'error': return 'text-error';
      case 'info': return 'text-info';
      default: return 'text-text-primary';
    }
  });
</script>

<div class="card card-sm">
  <div class="flex items-center gap-2 mb-1">
    {#if icon}{@const Icon = icon}<Icon class="w-4 h-4 text-text-tertiary" />{/if}
    <span class="text-2xs font-medium uppercase tracking-wide text-text-secondary">{label}</span>
  </div>
  <div class="text-2xl font-bold {valueColor}">{value}</div>
  {#if subtitle}
    <div class="text-xs text-text-tertiary mt-0.5">{subtitle}</div>
  {/if}
</div>

// apps/frontend/concord-app/src/app/components/system/metric-card.tsx
import { type LucideIcon } from 'lucide-react';

interface MetricCardProps {
  label: string;
  value: string | number;
  icon?: LucideIcon;
  subtitle?: string;
  status?: 'success' | 'warning' | 'error' | 'info' | 'neutral';
}

export function MetricCard({ label, value, icon: Icon, subtitle, status = 'neutral' }: MetricCardProps) {
  const statusColors: Record<string, string> = {
    success: 'text-success',
    warning: 'text-warning',
    error: 'text-error',
    info: 'text-info',
    neutral: 'text-text-primary',
  };

  return (
    <div className="rounded-lg border border-border bg-surface-1 p-4">
      <div className="flex items-center justify-between">
        <span className="text-xs font-medium uppercase tracking-wide text-text-tertiary">
          {label}
        </span>
        {Icon && <Icon size={14} className="text-text-tertiary" />}
      </div>
      <div className={`mt-1 text-2xl font-semibold ${statusColors[status]}`}>
        {value}
      </div>
      {subtitle && (
        <div className="mt-0.5 text-xs text-text-tertiary">{subtitle}</div>
      )}
    </div>
  );
}
