// apps/frontend/concord-app-svelte/src/lib/components/system/resource-table.svelte
<script lang="ts" generics="T">
  import type { Snippet } from 'svelte';

  interface Column<T> {
    key: string;
    header: string;
    render: Snippet<[T]>;
    className?: string;
  }

  interface Props {
    columns: Column<T>[];
    data: T[];
    keyFn: (item: T) => string;
    onRowClick?: (item: T) => void;
    emptyMessage?: string;
  }

  let { columns, data, keyFn, onRowClick, emptyMessage = 'No items found' }: Props = $props();

  function handleKeyDown(e: KeyboardEvent, item: T) {
    if (onRowClick && (e.key === 'Enter' || e.key === ' ')) {
      e.preventDefault();
      onRowClick(item);
    }
  }
</script>

<div class="table-wrapper">
  <table class="table">
    <thead>
      <tr class="border-b border-border">
        {#each columns as col}
          <th class="table-header {col.className ?? ''}">
            {col.header}
          </th>
        {/each}
      </tr>
    </thead>
    <tbody>
      {#if data.length === 0}
        <tr>
          <td colspan={columns.length} class="table-empty">
            {emptyMessage}
          </td>
        </tr>
      {:else}
        {#each data as item (keyFn(item))}
          <tr
            class="table-row {onRowClick ? 'table-row-interactive' : ''}"
            onclick={() => onRowClick?.(item)}
            onkeydown={(e) => handleKeyDown(e, item)}
            tabindex={onRowClick ? 0 : undefined}
            role={onRowClick ? 'button' : undefined}
          >
            {#each columns as col}
              <td class="table-cell {col.className ?? ''}">
                {@render col.render(item)}
              </td>
            {/each}
          </tr>
        {/each}
      {/if}
    </tbody>
  </table>
</div>

// apps/frontend/concord-app/src/app/components/system/resource-table.tsx
import { type KeyboardEvent, type ReactNode } from 'react';

export interface Column<T> {
  key: string;
  header: string;
  render: (item: T) => ReactNode;
  className?: string;
}

interface ResourceTableProps<T> {
  columns: Column<T>[];
  data: T[];
  keyFn: (item: T, index: number) => string;
  onRowClick?: (item: T) => void;
  emptyMessage?: string;
}

export function ResourceTable<T>({
  columns,
  data,
  keyFn,
  onRowClick,
  emptyMessage = 'No resources found',
}: ResourceTableProps<T>) {
  if (data.length === 0) {
    return (
      <div className="py-12 text-center text-sm text-text-tertiary">
        {emptyMessage}
      </div>
    );
  }

  return (
    <div className="overflow-x-auto rounded-lg border border-border">
      <table className="w-full text-left text-sm">
        <thead>
          <tr className="border-b border-border bg-surface-2">
            {columns.map((col) => (
              <th
                key={col.key}
                className={`px-3 py-2 text-2xs font-medium uppercase tracking-wide text-text-tertiary ${col.className || ''}`}
              >
                {col.header}
              </th>
            ))}
          </tr>
        </thead>
        <tbody className="divide-y divide-border-subtle">
          {data.map((item, idx) => (
            <tr
              key={keyFn(item, idx)}
              className={`bg-surface-1 transition-colors ${
                onRowClick ? 'cursor-pointer hover:bg-surface-2' : ''
              }`}
              onClick={() => onRowClick?.(item)}
              {...(onRowClick ? { tabIndex: 0, onKeyDown: (e: KeyboardEvent) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); onRowClick(item); } } } : {})}
            >
              {columns.map((col) => (
                <td key={col.key} className={`px-3 py-2 ${col.className || ''}`}>
                  {col.render(item)}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
