// apps/frontend/concord-app/src/app/pages/system/rbac.tsx
import { useState } from 'react';
import { useFetchData } from '../../hooks/use-fetch-data';
import { ErrorAlert } from '../../components/ui/error-alert';
import { LoadingState } from '../../components/ui/loading-state';
import { NamespaceSelector } from '../../components/system/namespace-selector';
import { ResourceTable, type Column } from '../../components/system/resource-table';
import { ResourceAge } from '../../components/system/resource-age';
import { Role, RoleBinding, ServiceAccount } from '../../types/models';

type RbacTab = 'roles' | 'clusterroles' | 'bindings' | 'clusterrolebindings' | 'serviceaccounts';

type RbacData = Role | RoleBinding | ServiceAccount;

const TABS: { key: RbacTab; label: string; namespaced: boolean }[] = [
  { key: 'roles', label: 'Roles', namespaced: true },
  { key: 'clusterroles', label: 'ClusterRoles', namespaced: false },
  { key: 'bindings', label: 'RoleBindings', namespaced: true },
  { key: 'clusterrolebindings', label: 'ClusterRoleBindings', namespaced: false },
  { key: 'serviceaccounts', label: 'ServiceAccounts', namespaced: true },
];

const API_PATHS: Record<RbacTab, string> = {
  roles: '/v2/system/rbac/roles',
  clusterroles: '/v2/system/rbac/clusterroles',
  bindings: '/v2/system/rbac/bindings',
  clusterrolebindings: '/v2/system/rbac/clusterrolebindings',
  serviceaccounts: '/v2/system/rbac/serviceaccounts',
};

function isRole(item: RbacData): item is Role {
  return 'rules' in item;
}

function isRoleBinding(item: RbacData): item is RoleBinding {
  return 'roleRef' in item;
}

function isServiceAccount(item: RbacData): item is ServiceAccount {
  return 'secrets' in item;
}

export function RbacPage() {
  const [tab, setTab] = useState<RbacTab>('roles');
  const [namespace, setNamespace] = useState('');
  const [expandedRule, setExpandedRule] = useState<string | null>(null);

  const isNamespaced = TABS.find((t) => t.key === tab)!.namespaced;

  const url = (() => {
    const params = new URLSearchParams();
    if (namespace && isNamespaced) {
      params.set('namespace', namespace);
    }
    const qs = params.toString();
    return qs ? `${API_PATHS[tab]}?${qs}` : API_PATHS[tab];
  })();

  const { data, loading, error } = useFetchData<RbacData[]>(url);

  const items = data ?? [];

  const roleColumns: Column<Role>[] = [
    {
      key: 'name',
      header: 'Name',
      render: (r) => (
        <button
          onClick={(e) => {
            e.stopPropagation();
            setExpandedRule(expandedRule === r.name ? null : r.name);
          }}
          className="font-medium text-accent hover:underline"
        >
          {r.name}
        </button>
      ),
    },
    ...(tab === 'roles'
      ? [
          {
            key: 'namespace' as const,
            header: 'Namespace',
            render: (r: Role) => <span className="text-text-secondary">{r.namespace}</span>,
          },
        ]
      : []),
    {
      key: 'rules',
      header: 'Rules',
      render: (r) => (
        <span className="text-text-secondary">
          {r.rules.length} rule{r.rules.length !== 1 ? 's' : ''}
        </span>
      ),
    },
    {
      key: 'age',
      header: 'Age',
      render: (r) => <ResourceAge timestamp={r.createdAt} />,
    },
  ];

  const bindingColumns: Column<RoleBinding>[] = [
    {
      key: 'name',
      header: 'Name',
      render: (b) => <span className="font-medium text-text-primary">{b.name}</span>,
    },
    ...(tab === 'bindings'
      ? [
          {
            key: 'namespace' as const,
            header: 'Namespace',
            render: (b: RoleBinding) => <span className="text-text-secondary">{b.namespace}</span>,
          },
        ]
      : []),
    {
      key: 'roleRef',
      header: 'Role',
      render: (b) => (
        <span className="text-text-secondary">
          <span className="text-2xs text-text-tertiary">{b.roleRef.kind}/</span>
          {b.roleRef.name}
        </span>
      ),
    },
    {
      key: 'subjects',
      header: 'Subjects',
      render: (b) => (
        <div className="flex flex-wrap gap-1">
          {b.subjects.map((s, i) => (
            <span key={`${s.kind}-${s.name}-${s.namespace}-${i}`} className="rounded bg-surface-2 px-1.5 py-0.5 text-2xs text-text-secondary">
              {s.kind}/{s.name}
            </span>
          ))}
        </div>
      ),
    },
    {
      key: 'age',
      header: 'Age',
      render: (b) => <ResourceAge timestamp={b.createdAt} />,
    },
  ];

  const saColumns: Column<ServiceAccount>[] = [
    {
      key: 'name',
      header: 'Name',
      render: (sa) => <span className="font-medium text-text-primary">{sa.name}</span>,
    },
    {
      key: 'namespace',
      header: 'Namespace',
      render: (sa) => <span className="text-text-secondary">{sa.namespace}</span>,
    },
    {
      key: 'secrets',
      header: 'Secrets',
      render: (sa) => <span className="text-text-secondary">{sa.secrets.length}</span>,
    },
    {
      key: 'age',
      header: 'Age',
      render: (sa) => <ResourceAge timestamp={sa.createdAt} />,
    },
  ];

  const renderExpandedRules = (role: Role) => (
    <div className="mt-2 rounded border border-border bg-surface-2 p-3">
      <div className="mb-2 text-xs font-medium text-text-primary">Rules for {role.name}</div>
      <table className="w-full text-left text-xs">
        <thead>
          <tr className="border-b border-border-subtle">
            <th className="pb-1 pr-4 text-2xs font-medium text-text-tertiary">API Groups</th>
            <th className="pb-1 pr-4 text-2xs font-medium text-text-tertiary">Resources</th>
            <th className="pb-1 pr-4 text-2xs font-medium text-text-tertiary">Verbs</th>
            <th className="pb-1 text-2xs font-medium text-text-tertiary">Resource Names</th>
          </tr>
        </thead>
        <tbody className="divide-y divide-border-subtle">
          {role.rules.map((rule, i) => (
            <tr key={`${rule.apiGroups.join(',')}-${rule.resources.join(',')}-${rule.verbs.join(',')}-${i}`}>
              <td className="py-1.5 pr-4 font-mono text-text-secondary">
                {rule.apiGroups.map((g) => g || '""').join(', ')}
              </td>
              <td className="py-1.5 pr-4 font-mono text-text-secondary">
                {rule.resources.join(', ')}
              </td>
              <td className="py-1.5 pr-4">
                <div className="flex flex-wrap gap-1">
                  {rule.verbs.map((v) => (
                    <span
                      key={v}
                      className={`rounded px-1.5 py-0.5 text-2xs font-medium ${
                        v === '*'
                          ? 'bg-warning-muted text-warning'
                          : ['create', 'update', 'patch', 'delete', 'deletecollection'].includes(v)
                            ? 'bg-error-muted text-error'
                            : 'bg-success-muted text-success'
                      }`}
                    >
                      {v}
                    </span>
                  ))}
                </div>
              </td>
              <td className="py-1.5 font-mono text-text-tertiary">
                {rule.resourceNames.length > 0 ? rule.resourceNames.join(', ') : '-'}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );

  return (
    <div>
      <ErrorAlert message={error} />

      <div className="mb-4 flex items-center justify-between">
        <div className="flex gap-1 overflow-x-auto rounded-md bg-surface-2 p-0.5">
          {TABS.map((t) => (
            <button
              key={t.key}
              onClick={() => { setTab(t.key); setExpandedRule(null); }}
              className={`whitespace-nowrap rounded px-3 py-1.5 text-xs font-medium transition-all ${
                tab === t.key
                  ? 'bg-surface-1 text-text-primary shadow-sm'
                  : 'text-text-tertiary hover:text-text-secondary'
              }`}
            >
              {t.label}
            </button>
          ))}
        </div>

        {isNamespaced && (
          <NamespaceSelector value={namespace} onChange={setNamespace} />
        )}
      </div>

      {loading ? (
        <LoadingState message={`Loading ${tab}...`} />
      ) : (
        <>
          {(tab === 'roles' || tab === 'clusterroles') && (
            <>
              <ResourceTable
                columns={roleColumns}
                data={items.filter(isRole)}
                keyFn={(r) => `${r.namespace}/${r.name}`}
                emptyMessage={`No ${tab} found`}
              />
              {expandedRule && (
                <>
                  {items.filter(isRole)
                    .filter((r) => r.name === expandedRule)
                    .map((r) => (
                      <div key={r.name}>{renderExpandedRules(r)}</div>
                    ))}
                </>
              )}
            </>
          )}

          {(tab === 'bindings' || tab === 'clusterrolebindings') && (
            <ResourceTable
              columns={bindingColumns}
              data={items.filter(isRoleBinding)}
              keyFn={(b) => `${b.namespace}/${b.name}`}
              emptyMessage={`No ${tab} found`}
            />
          )}

          {tab === 'serviceaccounts' && (
            <ResourceTable
              columns={saColumns}
              data={items.filter(isServiceAccount)}
              keyFn={(sa) => `${sa.namespace}/${sa.name}`}
              emptyMessage="No service accounts found"
            />
          )}
        </>
      )}
    </div>
  );
}

// apps/frontend/concord-app-svelte/src/routes/system/rbac/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { ChevronRight, ChevronDown } from 'lucide-svelte';
  import { api } from '$lib/api';
  import ResourceAge from '$lib/components/system/resource-age.svelte';
  import NamespaceSelector from '$lib/components/system/namespace-selector.svelte';

  type TabType = 'roles' | 'clusterroles' | 'rolebindings' | 'clusterrolebindings' | 'serviceaccounts';

  interface RbacRule {
    apiGroups: string[];
    resources: string[];
    verbs: string[];
    resourceNames: string[];
  }

  interface Role {
    name: string;
    namespace?: string;
    rules: RbacRule[];
    createdAt: string;
  }

  interface RoleBinding {
    name: string;
    namespace?: string;
    roleRef: { kind: string; name: string };
    subjects: { kind: string; name: string; namespace?: string }[];
    createdAt: string;
  }

  interface ServiceAccount {
    name: string;
    namespace: string;
    secrets: string[];
    createdAt: string;
  }

  type RbacItem = Role | RoleBinding | ServiceAccount;

  let tab = $state<TabType>('roles');
  let namespace = $state('');
  let data = $state<RbacItem[]>([]);
  let loading = $state(true);
  let error = $state<string | null>(null);
  let expandedRule = $state<string | null>(null);

  const isNamespaced = $derived(
    tab === 'roles' || tab === 'rolebindings' || tab === 'serviceaccounts'
  );

  async function fetchData() {
    loading = true;
    error = null;
    try {
      let url = `/v2/system/rbac/${tab}`;
      if (isNamespaced && namespace) {
        url += `?namespace=${namespace}`;
      }
      const res = await api.get<{ data: RbacItem[] }>(url);
      if (res?.data) data = res.data;
    } catch (e) {
      error = e instanceof Error ? e.message : 'Failed to load RBAC data';
    } finally {
      loading = false;
    }
  }

  onMount(() => {
    fetchData();
  });

  $effect(() => {
    tab;
    namespace;
    fetchData();
  });

  function isRole(item: RbacItem): item is Role {
    return 'rules' in item;
  }

  function isRoleBinding(item: RbacItem): item is RoleBinding {
    return 'roleRef' in item;
  }

  function isServiceAccount(item: RbacItem): item is ServiceAccount {
    return 'secrets' in item;
  }

  function getVerbColor(verb: string): string {
    const writeVerbs = ['create', 'update', 'patch', 'delete', 'deletecollection'];
    if (verb === '*') return 'text-warning';
    if (writeVerbs.includes(verb)) return 'text-error';
    return 'text-success';
  }

  function toggleRule(name: string) {
    expandedRule = expandedRule === name ? null : name;
  }

  const tabs: { id: TabType; label: string }[] = [
    { id: 'roles', label: 'Roles' },
    { id: 'clusterroles', label: 'ClusterRoles' },
    { id: 'rolebindings', label: 'RoleBindings' },
    { id: 'clusterrolebindings', label: 'ClusterRoleBindings' },
    { id: 'serviceaccounts', label: 'ServiceAccounts' },
  ];
</script>

<div class="space-y-4">
  <!-- Tab Selector -->
  <div class="flex items-center gap-3 overflow-x-auto">
    <div class="flex rounded-lg bg-surface-2 p-1">
      {#each tabs as t}
        <button
          onclick={() => tab = t.id}
          class="px-3 py-1 text-sm font-medium rounded whitespace-nowrap {tab === t.id ? 'bg-surface-1 text-primary' : 'text-secondary hover:text-primary'}"
        >
          {t.label}
        </button>
      {/each}
    </div>
    {#if isNamespaced}
      <NamespaceSelector value={namespace} onchange={(ns) => namespace = ns} />
    {/if}
    <span class="text-sm text-secondary ml-auto">{data.length} items</span>
  </div>

  {#if loading}
    <div class="flex items-center justify-center py-12">
      <span class="text-secondary">Loading RBAC data...</span>
    </div>
  {:else if error}
    <div class="rounded-lg border border-error/20 bg-error/10 p-4 text-error">{error}</div>
  {:else}
    <div class="table-wrapper">
      <table class="table">
        <thead>
          <tr class="border-b border-border">
            {#if tab === 'roles' || tab === 'clusterroles'}
              <th class="table-header w-8 px-2"></th>
              <th class="table-header">Name</th>
              {#if tab === 'roles'}
                <th class="table-header">Namespace</th>
              {/if}
              <th class="table-header">Rules</th>
              <th class="table-header">Age</th>
            {:else if tab === 'rolebindings' || tab === 'clusterrolebindings'}
              <th class="table-header">Name</th>
              {#if tab === 'rolebindings'}
                <th class="table-header">Namespace</th>
              {/if}
              <th class="table-header">Role Ref</th>
              <th class="table-header">Subjects</th>
              <th class="table-header">Age</th>
            {:else}
              <th class="table-header">Name</th>
              <th class="table-header">Namespace</th>
              <th class="table-header">Secrets</th>
              <th class="table-header">Age</th>
            {/if}
          </tr>
        </thead>
        <tbody>
          {#each data as item}
            {#if isRole(item)}
              <tr
                class="table-row table-row-interactive"
                onclick={() => toggleRule(item.name)}
              >
                <td class="table-cell px-2">
                  {#if expandedRule === item.name}
                    <ChevronDown class="w-4 h-4 text-text-tertiary" />
                  {:else}
                    <ChevronRight class="w-4 h-4 text-text-tertiary" />
                  {/if}
                </td>
                <td class="table-cell font-medium text-text-primary">{item.name}</td>
                {#if tab === 'roles'}
                  <td class="table-cell text-text-secondary">{item.namespace}</td>
                {/if}
                <td class="table-cell text-text-secondary">{item.rules.length}</td>
                <td class="table-cell">
                  <ResourceAge timestamp={item.createdAt} />
                </td>
              </tr>
              {#if expandedRule === item.name}
                <tr class="bg-surface-0">
                  <td colspan={tab === 'roles' ? 5 : 4} class="px-6 py-3">
                    <table class="w-full text-xs">
                      <thead>
                        <tr class="text-text-tertiary">
                          <th class="px-2 py-1 text-left">API Groups</th>
                          <th class="px-2 py-1 text-left">Resources</th>
                          <th class="px-2 py-1 text-left">Verbs</th>
                          <th class="px-2 py-1 text-left">Resource Names</th>
                        </tr>
                      </thead>
                      <tbody>
                        {#each item.rules as rule}
                          <tr>
                            <td class="px-2 py-1 font-mono text-text-secondary">{rule.apiGroups.join(', ') || '*'}</td>
                            <td class="px-2 py-1 font-mono text-text-secondary">{rule.resources.join(', ')}</td>
                            <td class="px-2 py-1">
                              {#each rule.verbs as verb}
                                <span class="inline-block mr-1 {getVerbColor(verb)}">{verb}</span>
                              {/each}
                            </td>
                            <td class="px-2 py-1 font-mono text-text-secondary">{rule.resourceNames.join(', ') || '-'}</td>
                          </tr>
                        {/each}
                      </tbody>
                    </table>
                  </td>
                </tr>
              {/if}
            {:else if isRoleBinding(item)}
              <tr class="table-row">
                <td class="table-cell font-medium text-text-primary">{item.name}</td>
                {#if tab === 'rolebindings'}
                  <td class="table-cell text-text-secondary">{item.namespace}</td>
                {/if}
                <td class="table-cell font-mono text-text-secondary">
                  {item.roleRef.kind}/{item.roleRef.name}
                </td>
                <td class="table-cell">
                  <div class="flex flex-wrap gap-1">
                    {#each item.subjects as subject}
                      <span class="px-1.5 py-0.5 rounded text-2xs bg-surface-2 text-text-secondary">
                        {subject.kind}/{subject.name}
                      </span>
                    {/each}
                  </div>
                </td>
                <td class="table-cell">
                  <ResourceAge timestamp={item.createdAt} />
                </td>
              </tr>
            {:else if isServiceAccount(item)}
              <tr class="table-row">
                <td class="table-cell font-medium text-text-primary">{item.name}</td>
                <td class="table-cell text-text-secondary">{item.namespace}</td>
                <td class="table-cell text-text-secondary">{item.secrets.length}</td>
                <td class="table-cell">
                  <ResourceAge timestamp={item.createdAt} />
                </td>
              </tr>
            {/if}
          {:else}
            <tr>
              <td colspan="5" class="table-empty">No items found</td>
            </tr>
          {/each}
        </tbody>
      </table>
    </div>
  {/if}
</div>
