// apps/frontend/app/src/lib/components/products/firmware-app-list.svelte
<script lang="ts">
  import { Plus, ChevronDown, ChevronRight, Trash2, Download } from 'lucide-svelte';
  import { apiFetch, api } from '$lib/api';
  import StatusBadge from '$lib/components/ui/status-badge.svelte';
  import ErrorAlert from '$lib/components/ui/error-alert.svelte';
  import ConfirmDeleteDialog from '$lib/components/ui/confirm-delete-dialog.svelte';
  import FirmwareBuildUpload from './firmware-build-upload.svelte';
  import type { FirmwareBuild, ProductTarget } from '$lib/types/models';
  import type { ApiResponse } from '$lib/types';

  interface Props {
    productId: string;
    builds: FirmwareBuild[];
    targets: ProductTarget[];
    canManage: boolean;
    onRefresh: () => void;
  }

  let { productId, builds, targets, canManage, onRefresh }: Props = $props();

  let error = $state<string | null>(null);
  let expandedTargets = $state(new Set<string>());
  let uploadTargetId = $state<string | null>(null);
  let deleteTarget = $state<{ id: string; name: string } | null>(null);

  interface TargetGroup {
    targetId: string;
    targetLabel: string;
    builds: FirmwareBuild[];
  }

  const groupedBuilds = $derived.by(() => {
    const groups: Record<string, { builds: FirmwareBuild[]; label: string }> = {};
    // Initialize groups from available targets
    for (const t of targets) {
      groups[t.id] = { builds: [], label: `${t.soc} (${t.role})` };
    }
    // Add builds to groups (may include targets not in targets list)
    for (const build of builds) {
      if (build.targetId) {
        if (!groups[build.targetId]) {
          const t = build.target;
          groups[build.targetId] = {
            builds: [],
            label: t ? `${t.soc} (${t.role})` : build.targetId,
          };
        }
        groups[build.targetId].builds.push(build);
      }
    }
    return Object.entries(groups)
      .map(([targetId, group]) => ({
        targetId,
        targetLabel: group.label,
        builds: group.builds,
      }))
      .sort((a, b) => a.targetLabel.localeCompare(b.targetLabel));
  });

  // Builds with no target
  const untargetedBuilds = $derived(builds.filter((b) => !b.targetId));

  function toggleExpanded(targetId: string) {
    const next = new Set(expandedTargets);
    if (next.has(targetId)) {
      next.delete(targetId);
    } else {
      next.add(targetId);
    }
    expandedTargets = next;
  }

  async function handleDownload(buildId: string) {
    try {
      const res = await apiFetch<ApiResponse<{ url: string }>>(`/v2/products/firmware-builds/${buildId}/download`);
      window.open(res.data.url, '_blank');
    } catch (err) {
      error = err instanceof Error ? err.message : 'Failed to get download URL';
    }
  }

  function promptDelete(buildId: string) {
    const build = builds.find((b) => b.id === buildId);
    const label = build?.target ? `${build.target.soc} v${build.version}` : `v${build?.version}`;
    deleteTarget = { id: buildId, name: label };
  }

  async function handleDelete(buildId: string) {
    error = null;
    try {
      await api.delete(`/v2/products/${productId}/firmware-builds/${buildId}`);
      onRefresh();
    } catch (err) {
      error = err instanceof Error ? err.message : 'Failed to delete build';
    }
  }
</script>

<div>
  <ErrorAlert message={error} />

  <div class="mb-3 flex items-center justify-between">
    <h3 class="text-sm font-semibold text-text-primary">Firmware Builds</h3>
  </div>

  {#if targets.length === 0}
    <div class="py-6 text-center text-sm text-text-tertiary">
      Add targets first to manage firmware builds.
    </div>
  {:else}
    <div class="space-y-2">
      {#each groupedBuilds as group (group.targetId)}
        {@const isExpanded = expandedTargets.has(group.targetId)}
        <div class="rounded-lg border border-border bg-surface-0">
          <!-- Target header -->
          <div
            role="button"
            tabindex="0"
            onclick={() => toggleExpanded(group.targetId)}
            onkeydown={(e) => e.key === 'Enter' && toggleExpanded(group.targetId)}
            class="flex cursor-pointer items-center gap-3 px-3 py-2.5 hover:bg-surface-1"
          >
            {#if isExpanded}
              <ChevronDown size={16} class="shrink-0 text-text-tertiary" />
            {:else}
              <ChevronRight size={16} class="shrink-0 text-text-tertiary" />
            {/if}
            <span class="font-semibold text-text-primary text-sm">{group.targetLabel}</span>
            <span class="ml-auto text-2xs text-text-tertiary">
              {group.builds.length} build{group.builds.length !== 1 ? 's' : ''}
            </span>
          </div>

          {#if isExpanded}
            <div class="border-t border-border-subtle px-4 py-3">
              {#if group.builds.length > 0}
                <div class="table-wrapper">
                  <table class="table">
                    <thead>
                      <tr class="border-b border-border">
                        <th class="table-header">Version</th>
                        <th class="table-header">Status</th>
                        <th class="table-header">Mfg</th>
                        <th class="table-header text-right">Actions</th>
                      </tr>
                    </thead>
                    <tbody>
                      {#each group.builds as build (build.id)}
                        <tr class="table-row">
                          <td class="table-cell font-medium text-text-primary">
                            {build.version}
                            {#if build.modemFilename}
                              <span class="ml-1.5 rounded-full bg-surface-2 px-1.5 py-0.5 text-2xs font-medium text-text-secondary">+Modem</span>
                            {/if}
                          </td>
                          <td class="table-cell">
                            <StatusBadge status={build.status ?? 'UNKNOWN'} />
                          </td>
                          <td class="table-cell">
                            {#if build.isManufacturing}
                              <span class="rounded-full bg-warning-muted px-2 py-0.5 text-2xs font-medium text-warning">MFG</span>
                            {:else}
                              <span class="text-text-tertiary">-</span>
                            {/if}
                          </td>
                          <td class="table-cell text-right">
                            <div class="flex items-center justify-end gap-1">
                              <button
                                onclick={() => handleDownload(build.id)}
                                class="rounded p-1 text-text-tertiary hover:bg-surface-2 hover:text-accent"
                                title="Download"
                                aria-label="Download"
                              >
                                <Download size={16} />
                              </button>
                              {#if canManage}
                                <button
                                  onclick={() => promptDelete(build.id)}
                                  class="rounded p-1 text-text-tertiary hover:bg-error-muted hover:text-error"
                                  title="Delete"
                                  aria-label="Delete"
                                >
                                  <Trash2 size={16} />
                                </button>
                              {/if}
                            </div>
                          </td>
                        </tr>
                      {/each}
                    </tbody>
                  </table>
                </div>
              {:else}
                <div class="table-empty">No builds yet</div>
              {/if}

              {#if canManage}
                <div class="mt-3">
                  {#if uploadTargetId === group.targetId}
                    <FirmwareBuildUpload
                      {productId}
                      targetId={group.targetId}
                      onSuccess={() => { uploadTargetId = null; onRefresh(); }}
                      onCancel={() => (uploadTargetId = null)}
                    />
                  {:else}
                    <button
                      onclick={() => (uploadTargetId = group.targetId)}
                      class="flex items-center gap-1.5 rounded-lg bg-accent px-2.5 py-1.5 text-2xs font-medium text-white hover:bg-accent-hover"
                    >
                      <Plus size={16} />
                      Upload build
                    </button>
                  {/if}
                </div>
              {/if}
            </div>
          {/if}
        </div>
      {/each}
    </div>
  {/if}

  <ConfirmDeleteDialog
    open={!!deleteTarget}
    entityType="firmware build"
    entityName={deleteTarget?.name || ''}
    onConfirm={() => { handleDelete(deleteTarget!.id); deleteTarget = null; }}
    onCancel={() => (deleteTarget = null)}
  />
</div>

// apps/frontend/concord-app/src/app/pages/products/firmware-app-list.tsx
import { useState } from 'react';
import { Plus, X, Check, ChevronDown, ChevronRight, Pencil, Trash2, Cpu } from 'lucide-react';
import { api } from '../../api';
import { Select } from '../../components/ui/select';
import { ErrorAlert } from '../../components/ui/error-alert';
import { ConfirmDeleteDialog } from '../../components/ui/confirm-delete-dialog';
import { ApiResponse } from '../../types';
import { FirmwareBuildList } from './firmware-build-list';
import { type ChipsetConfig, FirmwareApp, FirmwareBuild, BoardRevision } from '../../types/models';

/** Group firmware apps by chipset. Apps with no chipset go into "Unassigned". */
function groupByChipset(apps: FirmwareApp[]): { chipset: string; apps: FirmwareApp[] }[] {
  const groups = new Map<string, FirmwareApp[]>();
  for (const app of apps) {
    const key = app.chipset || 'Unassigned';
    const list = groups.get(key) || [];
    list.push(app);
    groups.set(key, list);
  }
  // Sort groups: named chipsets alphabetically first, "Unassigned" last
  const entries = [...groups.entries()].sort((a, b) => {
    if (a[0] === 'Unassigned') return 1;
    if (b[0] === 'Unassigned') return -1;
    return a[0].localeCompare(b[0]);
  });
  return entries.map(([chipset, apps]) => ({ chipset, apps }));
}

export function FirmwareAppList({
  productId,
  apps,
  builds,
  boardRevisions,
  chipsetConfig,
  canManage,
  onRefresh,
}: {
  productId: string;
  apps: FirmwareApp[];
  builds: FirmwareBuild[];
  boardRevisions: BoardRevision[];
  chipsetConfig: ChipsetConfig | null;
  canManage: boolean;
  onRefresh: () => void;
}) {
  const [error, setError] = useState<string | null>(null);
  const [showForm, setShowForm] = useState(false);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [submitting, setSubmitting] = useState(false);
  const [expandedApps, setExpandedApps] = useState<Set<string>>(new Set());
  const [deleteTarget, setDeleteTarget] = useState<{ id: string; name: string } | null>(null);

  // Form fields
  const [formAppId, setFormAppId] = useState('');
  const [formName, setFormName] = useState('');
  const [formTargetMcu, setFormTargetMcu] = useState('');
  const [formChipset, setFormChipset] = useState('');
  const [formCloudDeviceType, setFormCloudDeviceType] = useState('');
  const [formCloudVariant, setFormCloudVariant] = useState('');
  const [formNotes, setFormNotes] = useState('');

  // Available chipset names and their target MCUs from backend config
  const chipsetNames = chipsetConfig?.chipsets.map((c) => c.name) || [];
  const getTargetMcus = (chipset: string) =>
    chipsetConfig?.chipsets.find((c) => c.name === chipset)?.targetMcus || [];

  const resetForm = () => {
    setFormAppId('');
    setFormName('');
    setFormTargetMcu('');
    setFormChipset('');
    setFormCloudDeviceType('');
    setFormCloudVariant('');
    setFormNotes('');
    setEditingId(null);
    setShowForm(false);
  };

  const startEdit = (a: FirmwareApp) => {
    setFormAppId(String(a.applicationId));
    setFormName(a.name);
    setFormTargetMcu(a.targetMcu || '');
    setFormChipset(a.chipset || '');
    setFormCloudDeviceType(a.coreCloudDeviceType || '');
    setFormCloudVariant(a.coreCloudVariant || '');
    setFormNotes(a.notes || '');
    setEditingId(a.id);
    setShowForm(true);
  };

  const toggleExpanded = (id: string) => {
    setExpandedApps((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);
    setSubmitting(true);

    const body: Record<string, unknown> = {
      name: formName,
      targetMcu: formTargetMcu || null,
      chipset: formChipset || null,
      coreCloudDeviceType: formCloudDeviceType || null,
      coreCloudVariant: formCloudVariant || null,
      notes: formNotes || null,
    };

    if (!editingId) {
      body.applicationId = parseInt(formAppId, 10);
    }

    try {
      if (editingId) {
        await api(`/v2/products/${productId}/firmware-apps/${editingId}`, {
          method: 'PUT',
          body: JSON.stringify(body),
        });
      } else {
        await api(`/v2/products/${productId}/firmware-apps`, {
          method: 'POST',
          body: JSON.stringify(body),
        });
      }
      resetForm();
      onRefresh();
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : 'Failed to save firmware application');
    } finally {
      setSubmitting(false);
    }
  };

  const handleDelete = async (id: string) => {
    setError(null);
    try {
      await api(`/v2/products/${productId}/firmware-apps/${id}`, { method: 'DELETE' });
      onRefresh();
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : 'Failed to delete');
    }
  };

  const chipsetGroups = groupByChipset(apps);

  return (
    <div>
      <div className="mb-3 flex items-center justify-between">
        <h3 className="text-sm font-semibold text-text-primary">Firmware Applications</h3>
        {canManage && !showForm && (
          <button
            onClick={() => { resetForm(); setShowForm(true); }}
            className="flex items-center gap-1.5 rounded-lg bg-accent px-2.5 py-1.5 text-2xs font-medium text-white hover:bg-accent-hover"
          >
            <Plus size={13} />
            Add application
          </button>
        )}
      </div>

      <ErrorAlert message={error} />

      {showForm && (
        <div className="mb-4 rounded-lg border border-border bg-surface-0 p-4">
          <div className="mb-3 flex items-center justify-between">
            <span className="text-2xs font-medium text-text-secondary">
              {editingId ? 'Edit application' : 'New application'}
            </span>
            <button onClick={resetForm} className="rounded p-1 text-text-tertiary hover:bg-surface-2 hover:text-text-primary">
              <X size={14} />
            </button>
          </div>
          <form onSubmit={handleSubmit}>
            <div className="mb-3 grid grid-cols-3 gap-3">
              <div>
                <label className="mb-1 block text-2xs font-medium text-text-tertiary">App ID</label>
                <input
                  type="number"
                  required
                  disabled={!!editingId}
                  value={formAppId}
                  onChange={(e) => setFormAppId(e.target.value)}
                  placeholder="e.g. 1"
                  className="w-full rounded-lg border border-border bg-surface-0 px-3 py-2 text-sm text-text-primary placeholder:text-text-tertiary focus:border-accent focus:outline-none disabled:opacity-50"
                />
              </div>
              <div>
                <label className="mb-1 block text-2xs font-medium text-text-tertiary">Name</label>
                <input
                  type="text"
                  required
                  value={formName}
                  onChange={(e) => setFormName(e.target.value)}
                  placeholder="e.g. Main App"
                  className="w-full rounded-lg border border-border bg-surface-0 px-3 py-2 text-sm text-text-primary placeholder:text-text-tertiary focus:border-accent focus:outline-none"
                />
              </div>
              <div>
                <label className="mb-1 block text-2xs font-medium text-text-tertiary">Chipset</label>
                <Select
                  value={formChipset}
                  onChange={(e) => {
                    setFormChipset(e.target.value);
                    // Reset target MCU when chipset changes
                    const mcus = getTargetMcus(e.target.value);
                    if (formTargetMcu && !mcus.includes(formTargetMcu)) {
                      setFormTargetMcu('');
                    }
                  }}
                >
                  <option value="">Select chipset...</option>
                  {chipsetNames.map((c) => (
                    <option key={c} value={c}>{c}</option>
                  ))}
                </Select>
              </div>
            </div>
            <div className="mb-3 grid grid-cols-3 gap-3">
              <div>
                <label className="mb-1 block text-2xs font-medium text-text-tertiary">Target MCU</label>
                <Select
                  value={formTargetMcu}
                  onChange={(e) => setFormTargetMcu(e.target.value)}
                >
                  <option value="">Select target MCU...</option>
                  {(formChipset ? getTargetMcus(formChipset) : chipsetConfig?.supportedSocs || []).map((m) => (
                    <option key={m} value={m}>{m}</option>
                  ))}
                </Select>
              </div>
              <div>
                <label className="mb-1 block text-2xs font-medium text-text-tertiary">Cloud Device Type</label>
                <input
                  type="text"
                  value={formCloudDeviceType}
                  onChange={(e) => setFormCloudDeviceType(e.target.value)}
                  className="w-full rounded-lg border border-border bg-surface-0 px-3 py-2 text-sm text-text-primary placeholder:text-text-tertiary focus:border-accent focus:outline-none"
                />
              </div>
              <div>
                <label className="mb-1 block text-2xs font-medium text-text-tertiary">Cloud Variant</label>
                <input
                  type="text"
                  value={formCloudVariant}
                  onChange={(e) => setFormCloudVariant(e.target.value)}
                  className="w-full rounded-lg border border-border bg-surface-0 px-3 py-2 text-sm text-text-primary placeholder:text-text-tertiary focus:border-accent focus:outline-none"
                />
              </div>
            </div>
            <div className="mb-3">
              <label className="mb-1 block text-2xs font-medium text-text-tertiary">Notes</label>
              <input
                type="text"
                value={formNotes}
                onChange={(e) => setFormNotes(e.target.value)}
                placeholder="Optional notes"
                className="w-full rounded-lg border border-border bg-surface-0 px-3 py-2 text-sm text-text-primary placeholder:text-text-tertiary focus:border-accent focus:outline-none"
              />
            </div>
            <div className="flex gap-2">
              <button type="submit" disabled={submitting} className="flex items-center gap-1.5 rounded-lg bg-accent px-3 py-1.5 text-2xs font-medium text-white hover:bg-accent-hover disabled:opacity-50">
                <Check size={12} />
                {submitting ? 'Saving...' : editingId ? 'Save' : 'Create'}
              </button>
              <button type="button" onClick={resetForm} className="rounded-lg px-3 py-1.5 text-2xs font-medium text-text-secondary hover:bg-surface-2">
                Cancel
              </button>
            </div>
          </form>
        </div>
      )}

      {apps.length > 0 ? (
        <div className="space-y-4">
          {chipsetGroups.map(({ chipset, apps: groupApps }) => (
            <div key={chipset}>
              {/* Chipset group header */}
              <div className="mb-2 flex items-center gap-2">
                <Cpu size={14} className="text-accent" />
                <span className="text-xs font-semibold text-text-primary">{chipset}</span>
                <span className="text-2xs text-text-tertiary">
                  {groupApps.length} app{groupApps.length !== 1 ? 's' : ''}
                </span>
                <div className="flex-1 border-t border-border-subtle" />
              </div>

              <div className="space-y-2">
                {groupApps.map((app) => {
                  const isExpanded = expandedApps.has(app.id);
                  const appBuilds = builds.filter((b) => b.applicationId === app.id);
                  // Filter board revisions to those whose SoCs include this app's target MCU
                  const relevantBoardRevisions = app.targetMcu
                    ? boardRevisions.filter((r) => r.chipsets.includes(app.targetMcu!))
                    : boardRevisions;

                  return (
                    <div key={app.id} className="rounded-lg border border-border bg-surface-0">
                      <div
                        className="flex cursor-pointer items-center gap-3 px-4 py-3 hover:bg-surface-1"
                        onClick={() => toggleExpanded(app.id)}
                      >
                        {isExpanded ? (
                          <ChevronDown size={14} className="shrink-0 text-text-tertiary" />
                        ) : (
                          <ChevronRight size={14} className="shrink-0 text-text-tertiary" />
                        )}
                        <span className="rounded bg-surface-2 px-1.5 py-0.5 text-2xs font-mono text-text-secondary">
                          ID {app.applicationId}
                        </span>
                        <span className="font-medium text-text-primary text-sm">{app.name}</span>
                        {app.targetMcu && (
                          <span className="rounded bg-surface-2 px-1.5 py-0.5 text-2xs text-text-tertiary">
                            {app.targetMcu}
                          </span>
                        )}
                        <span className="ml-auto text-2xs text-text-tertiary">
                          {appBuilds.length} build{appBuilds.length !== 1 ? 's' : ''}
                        </span>

                        {canManage && (
                          <div className="flex gap-1" onClick={(e) => e.stopPropagation()}>
                            <button
                              onClick={() => startEdit(app)}
                              className="rounded p-1 text-text-tertiary hover:bg-surface-2 hover:text-text-primary"
                              title="Edit"
                              aria-label="Edit"
                            >
                              <Pencil size={13} />
                            </button>
                            <button
                              onClick={() => setDeleteTarget({ id: app.id, name: app.name })}
                              className="rounded p-1 text-text-tertiary hover:bg-error-muted hover:text-error"
                              title="Delete"
                              aria-label="Delete"
                            >
                              <Trash2 size={13} />
                            </button>
                          </div>
                        )}
                      </div>

                      {isExpanded && app.notes && (
                        <div className="border-t border-border-subtle px-4 py-2 text-sm text-text-secondary">
                          {app.notes}
                        </div>
                      )}

                      {isExpanded && (
                        <div className="border-t border-border-subtle px-4 py-3">
                          <FirmwareBuildList
                            productId={productId}
                            applicationId={app.id}
                            builds={appBuilds}
                            boardRevisions={relevantBoardRevisions}
                            canManage={canManage}
                            onRefresh={onRefresh}
                          />
                        </div>
                      )}
                    </div>
                  );
                })}
              </div>
            </div>
          ))}
        </div>
      ) : (
        <div className="py-6 text-center text-sm text-text-tertiary">
          No firmware applications yet
        </div>
      )}

      <ConfirmDeleteDialog
        open={!!deleteTarget}
        entityType="firmware application"
        entityName={deleteTarget?.name || ''}
        onConfirm={() => { handleDelete(deleteTarget!.id); setDeleteTarget(null); }}
        onCancel={() => setDeleteTarget(null)}
      />
    </div>
  );
}
