// apps/frontend/concord-app-svelte/src/lib/components/layout.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { browser } from '$app/environment';
  import Sidebar from './sidebar.svelte';
  import SettingsModal from './settings/settings-modal.svelte';

  let { children } = $props();

  // Sidebar collapse state (persisted)
  let collapsed = $state(false);
  let settingsOpen = $state(false);

  onMount(() => {
    if (browser) {
      const stored = localStorage.getItem('concord-sidebar-collapsed');
      collapsed = stored === 'true';
    }
  });

  function toggleSidebar(): void {
    collapsed = !collapsed;
    if (browser) {
      localStorage.setItem('concord-sidebar-collapsed', String(collapsed));
    }
  }

  const sidebarWidth = $derived(collapsed ? 'var(--sidebar-collapsed-width)' : 'var(--sidebar-width)');
</script>

<div class="flex min-h-screen bg-surface-0">
  <Sidebar
    {collapsed}
    onToggle={toggleSidebar}
    onSettingsClick={() => (settingsOpen = true)}
  />

  <main
    class="flex-1 transition-[margin] duration-200 ease-out"
    style:margin-left={sidebarWidth}
  >
    <!-- Content wrapper with consistent padding (24px = space-6) -->
    <div class="mx-auto max-w-7xl px-6 py-6">
      {@render children()}
    </div>
  </main>
</div>

{#if settingsOpen}
  <SettingsModal onClose={() => (settingsOpen = false)} />
{/if}

// apps/frontend/concord-app/src/app/components/layout.tsx
import { useState } from 'react';
import { Outlet } from 'react-router-dom';
import { Sidebar } from './sidebar';
import { SettingsModal } from './settings/settings-modal';

export function Layout() {
  const [collapsed, setCollapsed] = useState(() => {
    return localStorage.getItem('concord-sidebar') === 'collapsed';
  });
  const [settingsOpen, setSettingsOpen] = useState(false);

  const handleToggle = () => {
    setCollapsed((prev) => {
      const next = !prev;
      localStorage.setItem('concord-sidebar', next ? 'collapsed' : 'expanded');
      return next;
    });
  };

  return (
    <div className="flex min-h-screen">
      <Sidebar
        collapsed={collapsed}
        onToggle={handleToggle}
        onSettingsClick={() => setSettingsOpen(true)}
      />
      <main
        className="flex-1 transition-[margin-left] duration-200 ease-in-out"
        style={{ marginLeft: collapsed ? 64 : 260 }}
      >
        <div className="mx-auto max-w-6xl px-8 py-8">
          <Outlet />
        </div>
      </main>
      {settingsOpen && <SettingsModal onClose={() => setSettingsOpen(false)} />}
    </div>
  );
}
