// apps/frontend/concord-app-svelte/src/lib/components/sidebar.svelte
<script lang="ts">
  import { page } from '$app/stores';
  import { goto } from '$app/navigation';
  import { browser } from '$app/environment';
  import {
    LayoutDashboard,
    FlaskConical,
    Server,
    Wrench,
    Settings,
    Users,
    ShieldCheck,
    Cpu,
    Package,
    GitBranch,
    BookOpen,
    History,
    LogOut,
    PanelLeftClose,
    Monitor
  } from 'lucide-svelte';
  import { PUBLIC_APP_VERSION } from '$env/static/public';
  import { getTheme } from '$lib/stores/theme.svelte';
  import { getAuth } from '$lib/stores/auth.svelte';
  import ConcordLogo from '$lib/components/concord-logo.svelte';

  interface NavItem {
    to: string;
    icon: typeof LayoutDashboard;
    label: string;
    permission?: string;
  }

  let {
    collapsed,
    onToggle,
    onSettingsClick
  }: {
    collapsed: boolean;
    onToggle: () => void;
    onSettingsClick: () => void;
  } = $props();

  const theme = getTheme();
  const auth = getAuth();

  type Mode = 'manufacturing' | 'validation';
  const STORAGE_KEY = 'concord-mode';

  function getInitialMode(): Mode {
    if (!browser) return 'manufacturing';
    const stored = localStorage.getItem(STORAGE_KEY);
    if (stored === 'manufacturing' || stored === 'validation') return stored;
    return 'manufacturing';
  }

  let mode = $state<Mode>(getInitialMode());

  function handleModeChange(newMode: Mode): void {
    mode = newMode;
    if (browser) {
      localStorage.setItem(STORAGE_KEY, newMode);
    }
  }

  const navItems = $derived.by(() => {
    const items: NavItem[] = [
      { to: '/', icon: LayoutDashboard, label: 'Dashboard' },
      { to: '/fixtures', icon: Wrench, label: 'Fixtures' },
    ];
    if (mode === 'validation') {
      items.push({ to: '/racks', icon: Monitor, label: 'Racks' });
    }
    items.push({ to: '/tests', icon: FlaskConical, label: 'Tests' });
    return items;
  });

  const adminItems: NavItem[] = [
    { to: '/nodes', icon: Server, label: 'Nodes', permission: 'Concord.Admin.Nodes.View' },
    { to: '/system', icon: Monitor, label: 'System', permission: 'Concord.Admin.System.View' },
    { to: '/inventory', icon: Cpu, label: 'Inventory', permission: 'Concord.Admin.Inventory.View' },
    { to: '/codebases', icon: GitBranch, label: 'Codebases', permission: 'Concord.Admin.Codebases.View' },
    { to: '/products', icon: Package, label: 'Products', permission: 'Concord.Admin.Products.View' },
    { to: '/history', icon: History, label: 'History', permission: 'Concord.Admin.History.View' },
    { to: '/guides', icon: BookOpen, label: 'Guides' },
    { to: '/users', icon: Users, label: 'Users', permission: 'Concord.Admin.Users.View' },
    { to: '/permission-sets', icon: ShieldCheck, label: 'Permission Sets', permission: 'Concord.Admin.Users.View' },
  ];

  const visibleAdminItems = $derived(
    adminItems.filter(item => !item.permission || auth.hasPermission(item.permission))
  );

  const isAdmin = $derived(visibleAdminItems.length > 0);

  function handleLogout(): void {
    auth.logout();
    goto('/login');
  }

  function isActive(path: string, end = false): boolean {
    if (end) {
      return $page.url.pathname === path;
    }
    return $page.url.pathname === path || $page.url.pathname.startsWith(path + '/');
  }
</script>

{#snippet navLink(item: NavItem, exactMatch?: boolean)}
  {@const active = isActive(item.to, exactMatch)}
  <a
    href={item.to}
    ondblclick={onToggle}
    title={collapsed ? item.label : undefined}
    class="group relative flex items-center rounded-lg text-sm font-medium transition-all"
    class:justify-center={collapsed}
    class:px-0={collapsed}
    class:py-2={true}
    class:gap-3={!collapsed}
    class:px-3={!collapsed}
    class:bg-sidebar-active={active}
    class:text-accent={active}
    class:text-text-secondary={!active}
    class:hover:bg-sidebar-hover={!active}
    class:hover:text-text-primary={!active}
  >
    {#if active}
      <div class="absolute left-0 top-1/2 h-4 w-0.5 -translate-y-1/2 rounded-r bg-accent"></div>
    {/if}
    <item.icon size={18} strokeWidth={1.75} class="shrink-0" />
    {#if !collapsed}
      <span class="truncate">{item.label}</span>
    {/if}
  </a>
{/snippet}

<aside
  class="fixed inset-y-0 left-0 z-fixed flex flex-col border-r border-border bg-sidebar-bg transition-[width] duration-200 ease-out"
  style:width={collapsed ? 'var(--sidebar-collapsed-width)' : 'var(--sidebar-width)'}
>
  <div
    class="flex h-16 items-center"
    class:justify-center={collapsed}
    class:px-3={collapsed}
    class:justify-between={!collapsed}
    class:px-5={!collapsed}
  >
    {#if collapsed}
      <button
        onclick={onToggle}
        title="Expand sidebar"
        aria-label="Expand sidebar"
        class="flex flex-col items-center justify-center gap-1"
      >
        <ConcordLogo size={24} class="text-accent" />
        <img
          src={theme.theme === 'dark' ? '/assets/ck-logo.png' : '/assets/ck-logo-dark.png'}
          alt="CK"
          class="h-3 opacity-60"
        />
      </button>
    {:else}
      <div class="flex items-center gap-2.5">
        <ConcordLogo size={32} class="text-accent" />
        <div class="flex flex-col">
          <img
            src={theme.theme === 'dark' ? '/assets/corekinect-logo.png' : '/assets/corekinect-logo-dark.png'}
            alt="CoreKinect"
            class="h-4"
          />
        </div>
      </div>
      <button
        onclick={onToggle}
        title="Collapse sidebar"
        aria-label="Collapse sidebar"
        class="flex h-7 w-7 items-center justify-center rounded-lg text-text-tertiary transition-colors hover:bg-sidebar-hover hover:text-text-primary"
      >
        <PanelLeftClose size={16} strokeWidth={1.75} />
      </button>
    {/if}
  </div>

  <div class="border-t border-border" class:mx-2={collapsed} class:mx-4={!collapsed}></div>

  <div
    class="flex rounded-lg bg-surface-2 p-0.5"
    class:mx-2={collapsed}
    class:mt-3={true}
    class:mx-4={!collapsed}
  >
    <button
      onclick={() => handleModeChange('manufacturing')}
      class="flex-1 rounded-md text-center text-2xs font-medium transition-all"
      class:px-1={collapsed}
      class:py-1.5={true}
      class:px-2={!collapsed}
      class:bg-accent-muted={mode === 'manufacturing'}
      class:text-accent={mode === 'manufacturing'}
      class:shadow-sm={mode === 'manufacturing'}
      class:text-text-tertiary={mode !== 'manufacturing'}
      class:hover:text-text-secondary={mode !== 'manufacturing'}
    >
      {collapsed ? 'M' : 'Manufacturing'}
    </button>
    <button
      onclick={() => handleModeChange('validation')}
      class="flex-1 rounded-md text-center text-2xs font-medium transition-all"
      class:px-1={collapsed}
      class:py-1.5={true}
      class:px-2={!collapsed}
      class:bg-accent-muted={mode === 'validation'}
      class:text-accent={mode === 'validation'}
      class:shadow-sm={mode === 'validation'}
      class:text-text-tertiary={mode !== 'validation'}
      class:hover:text-text-secondary={mode !== 'validation'}
    >
      {collapsed ? 'V' : 'Validation'}
    </button>
  </div>

  <nav
    class="flex-1 space-y-1 pt-4 pb-2"
    class:px-2={collapsed}
    class:px-3={!collapsed}
  >
    {#each navItems as item}
      {@render navLink(item, item.to === '/')}
    {/each}

    {#if isAdmin}
      <div class="pt-4">
        <div class="border-t border-border" class:mx-0={collapsed} class:mx-1={!collapsed}></div>
        <div class="pt-4">
          {#if !collapsed}
            <span class="mb-2 block px-3 text-2xs font-medium uppercase tracking-widest text-text-tertiary">
              Admin
            </span>
          {/if}

          {#each visibleAdminItems as item}
            {@render navLink(item)}
          {/each}
        </div>
      </div>
    {/if}
  </nav>

  <div
    class="border-t border-border space-y-1"
    class:p-2={collapsed}
    class:p-3={!collapsed}
  >
    <button
      onclick={onSettingsClick}
      ondblclick={onToggle}
      title={collapsed ? 'Settings' : undefined}
      class="group relative flex w-full items-center rounded-lg text-sm font-medium transition-all text-text-secondary hover:bg-sidebar-hover hover:text-text-primary"
      class:justify-center={collapsed}
      class:px-0={collapsed}
      class:py-2={true}
      class:gap-3={!collapsed}
      class:px-3={!collapsed}
    >
      <Settings size={18} strokeWidth={1.75} class="shrink-0" />
      {#if !collapsed}<span class="truncate">Settings</span>{/if}
    </button>

    {#if auth.user}
      <div
        class="mt-1 flex items-center rounded-lg"
        class:justify-center={collapsed}
        class:py-2={collapsed}
        class:gap-2={!collapsed}
        class:px-3={!collapsed}
      >
        <div
          class="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-accent-muted text-2xs font-semibold text-accent"
          title={collapsed
            ? `${auth.user.name}${auth.user.permissionSetName ? ` (${auth.user.permissionSetName})` : ''}`
            : undefined}
        >
          {auth.user.name.charAt(0).toUpperCase()}
        </div>
        {#if !collapsed}
          <div class="min-w-0 flex-1">
            <div class="truncate text-2xs font-medium text-text-primary">
              {auth.user.name}
            </div>
            <div class="truncate text-2xs text-text-tertiary">
              {auth.user.permissionSetName || auth.user.email}
            </div>
          </div>
          <button
            onclick={handleLogout}
            title="Sign out"
            aria-label="Log out"
            class="shrink-0 rounded p-1 text-text-tertiary transition-colors hover:bg-sidebar-hover hover:text-text-primary"
          >
            <LogOut size={16} strokeWidth={1.75} />
          </button>
        {/if}
      </div>
    {/if}

    {#if !collapsed && PUBLIC_APP_VERSION}
      <div class="px-3 pt-1 text-center">
        <span class="text-2xs text-text-tertiary opacity-50">v{PUBLIC_APP_VERSION}</span>
      </div>
    {/if}
  </div>
</aside>

// apps/frontend/concord-app/src/app/components/sidebar.tsx
import { useState } from 'react';
import { NavLink, useNavigate } from 'react-router-dom';
import {
  LayoutDashboard,
  FlaskConical,
  Container,
  Server,
  ClipboardCheck,
  ScrollText,
  BarChart3,
  Settings,
  Users,
  ShieldCheck,
  Cpu,
  Package,
  GitBranch,
  BookOpen,
  History,
  LogOut,
  PanelLeftClose,
  Monitor,
} from 'lucide-react';
import { useTheme } from '../theme-provider';
import { useAuth } from '../auth-provider';
import logoDark from '../../assets/corekinect-logo.png';
import logoLight from '../../assets/corekinect-logo-dark.png';
import ckDark from '../../assets/ck-logo.png';
import ckLight from '../../assets/ck-logo-dark.png';

type Mode = 'manufacturing' | 'validation';

const STORAGE_KEY = 'concord-mode';

function getInitialMode(): Mode {
  const stored = localStorage.getItem(STORAGE_KEY);
  if (stored === 'manufacturing' || stored === 'validation') return stored;
  return 'manufacturing';
}

const manufacturingNav = [
  { to: '/', icon: LayoutDashboard, label: 'Dashboard' },
  { to: '/tests', icon: FlaskConical, label: 'Tests' },
  { to: '/deployments', icon: Container, label: 'Deployments' },
  { to: '/nodes', icon: Server, label: 'Nodes' },
  { to: '/results', icon: ClipboardCheck, label: 'Test Results' },
  { to: '/logs', icon: ScrollText, label: 'Logs' },
  { to: '/statistics', icon: BarChart3, label: 'Statistics' },
];

const validationNav = [
  { to: '/', icon: LayoutDashboard, label: 'Dashboard' },
  { to: '/tests', icon: FlaskConical, label: 'Tests' },
  { to: '/deployments', icon: Container, label: 'Deployments' },
  { to: '/nodes', icon: Server, label: 'Nodes' },
  { to: '/results', icon: ClipboardCheck, label: 'Test Results' },
  { to: '/logs', icon: ScrollText, label: 'Logs' },
  { to: '/statistics', icon: BarChart3, label: 'Statistics' },
];

function ModeToggle({
  mode,
  onModeChange,
  collapsed,
}: {
  mode: Mode;
  onModeChange: (mode: Mode) => void;
  collapsed: boolean;
}) {
  return (
    <div
      className={[
        'flex rounded-lg bg-surface-2 p-0.5',
        collapsed ? 'mx-2 mt-3' : 'mx-4 mt-3',
      ].join(' ')}
    >
      <button
        onClick={() => onModeChange('manufacturing')}
        className={[
          'flex-1 rounded-md text-center text-2xs font-medium transition-all',
          collapsed ? 'px-1 py-1.5' : 'px-2 py-1.5',
          mode === 'manufacturing'
            ? 'bg-accent-muted text-accent shadow-sm'
            : 'text-text-tertiary hover:text-text-secondary',
        ].join(' ')}
      >
        {collapsed ? 'M' : 'Manufacturing'}
      </button>
      <button
        onClick={() => onModeChange('validation')}
        className={[
          'flex-1 rounded-md text-center text-2xs font-medium transition-all',
          collapsed ? 'px-1 py-1.5' : 'px-2 py-1.5',
          mode === 'validation'
            ? 'bg-accent-muted text-accent shadow-sm'
            : 'text-text-tertiary hover:text-text-secondary',
        ].join(' ')}
      >
        {collapsed ? 'V' : 'Validation'}
      </button>
    </div>
  );
}

function SidebarLink({
  to,
  icon: Icon,
  label,
  end,
  collapsed,
  onDoubleClick,
}: {
  to: string;
  icon: React.ComponentType<{ size: number; strokeWidth: number; className?: string }>;
  label: string;
  end?: boolean;
  collapsed: boolean;
  onDoubleClick: () => void;
}) {
  return (
    <NavLink
      to={to}
      end={end}
      title={collapsed ? label : undefined}
      onDoubleClick={onDoubleClick}
      className={({ isActive }) =>
        [
          'group relative flex items-center rounded-lg text-[13px] font-medium transition-all',
          collapsed ? 'justify-center px-0 py-2' : 'gap-3 px-3 py-2',
          isActive
            ? 'bg-sidebar-active text-accent'
            : 'text-text-secondary hover:bg-sidebar-hover hover:text-text-primary',
        ].join(' ')
      }
    >
      {({ isActive }) => (
        <>
          {isActive && (
            <div className="absolute left-0 top-1/2 h-4 w-0.5 -translate-y-1/2 rounded-r bg-accent" />
          )}
          <Icon size={18} strokeWidth={1.75} className="shrink-0" />
          {!collapsed && <span className="truncate">{label}</span>}
        </>
      )}
    </NavLink>
  );
}

export function Sidebar({
  collapsed,
  onToggle,
  onSettingsClick,
}: {
  collapsed: boolean;
  onToggle: () => void;
  onSettingsClick: () => void;
}) {
  const { theme } = useTheme();
  const { user, logout, hasPermission } = useAuth();
  const navigate = useNavigate();
  const [mode, setMode] = useState<Mode>(getInitialMode);

  const handleModeChange = (newMode: Mode) => {
    setMode(newMode);
    localStorage.setItem(STORAGE_KEY, newMode);
  };

  const navItems = mode === 'manufacturing' ? manufacturingNav : validationNav;

  const handleLogout = () => {
    logout();
    navigate('/login');
  };

  const isAdmin = hasPermission('Concord.Admin.Users.View') || hasPermission('Concord.Admin.Inventory.View') || hasPermission('Concord.Admin.Codebases.View') || hasPermission('Concord.Admin.Products.View') || hasPermission('Concord.Admin.History.View') || hasPermission('Concord.Admin.System.View');

  return (
    <aside
      className={[
        'fixed inset-y-0 left-0 z-30 flex flex-col border-r border-border bg-sidebar-bg transition-[width] duration-200 ease-in-out',
        collapsed ? 'w-16' : 'w-sidebar',
      ].join(' ')}
    >
      {/* Brand + collapse toggle */}
      <div
        className={[
          'flex h-14 items-center',
          collapsed ? 'justify-center px-2' : 'justify-between px-5',
        ].join(' ')}
      >
        {collapsed ? (
          <button
            onClick={onToggle}
            title="Expand sidebar"
            aria-label="Expand sidebar"
            className="flex items-center justify-center"
          >
            <img
              src={theme === 'dark' ? ckDark : ckLight}
              alt="CoreKinect"
              className="h-4"
            />
          </button>
        ) : (
          <>
            <div className="flex flex-col gap-1.5">
              <img
                src={theme === 'dark' ? logoDark : logoLight}
                alt="CoreKinect"
                className="h-3.5"
              />
              <span className="text-2xs font-medium tracking-widest uppercase text-text-tertiary">
                Concord
              </span>
            </div>
            <button
              onClick={onToggle}
              title="Collapse sidebar"
              aria-label="Collapse sidebar"
              className="flex h-7 w-7 items-center justify-center rounded-lg text-text-tertiary transition-colors hover:bg-sidebar-hover hover:text-text-primary"
            >
              <PanelLeftClose size={16} strokeWidth={1.75} />
            </button>
          </>
        )}
      </div>

      {/* Divider */}
      <div
        className={
          collapsed
            ? 'mx-2 border-t border-border'
            : 'mx-4 border-t border-border'
        }
      />

      {/* Mode toggle */}
      <ModeToggle mode={mode} onModeChange={handleModeChange} collapsed={collapsed} />

      {/* Navigation */}
      <nav
        className={[
          'flex-1 space-y-0.5 pt-4 pb-2',
          collapsed ? 'px-2' : 'px-3',
        ].join(' ')}
      >
        {navItems.map(({ to, icon, label }) => (
          <SidebarLink
            key={to}
            to={to}
            icon={icon}
            label={label}
            end={to === '/'}
            collapsed={collapsed}
            onDoubleClick={onToggle}
          />
        ))}

        {/* Admin section */}
        {isAdmin && (
          <div className="pt-4">
            <div
              className={[
                'border-t border-border',
                collapsed ? 'mx-0' : 'mx-1',
              ].join(' ')}
            />
            <div className="pt-4">
              {!collapsed && (
                <span className="mb-2 block px-3 text-2xs font-medium uppercase tracking-widest text-text-tertiary">
                  Admin
                </span>
              )}
              {hasPermission('Concord.Admin.System.View') && (
                <SidebarLink
                  to="/system"
                  icon={Monitor}
                  label="System"
                  collapsed={collapsed}
                  onDoubleClick={onToggle}
                />
              )}
              {hasPermission('Concord.Admin.Inventory.View') && (
                <SidebarLink
                  to="/inventory"
                  icon={Cpu}
                  label="Inventory"
                  collapsed={collapsed}
                  onDoubleClick={onToggle}
                />
              )}
              {hasPermission('Concord.Admin.Codebases.View') && (
                <SidebarLink
                  to="/codebases"
                  icon={GitBranch}
                  label="Codebases"
                  collapsed={collapsed}
                  onDoubleClick={onToggle}
                />
              )}
              {hasPermission('Concord.Admin.Products.View') && (
                <SidebarLink
                  to="/products"
                  icon={Package}
                  label="Products"
                  collapsed={collapsed}
                  onDoubleClick={onToggle}
                />
              )}
              {hasPermission('Concord.Admin.History.View') && (
                <SidebarLink
                  to="/history"
                  icon={History}
                  label="History"
                  collapsed={collapsed}
                  onDoubleClick={onToggle}
                />
              )}
              <SidebarLink
                to="/guides"
                icon={BookOpen}
                label="Guides"
                collapsed={collapsed}
                onDoubleClick={onToggle}
              />
              {hasPermission('Concord.Admin.Users.View') && (
                <SidebarLink
                  to="/users"
                  icon={Users}
                  label="Users"
                  collapsed={collapsed}
                  onDoubleClick={onToggle}
                />
              )}
              {hasPermission('Concord.Admin.Users.View') && (
                <SidebarLink
                  to="/permission-sets"
                  icon={ShieldCheck}
                  label="Permission Sets"
                  collapsed={collapsed}
                  onDoubleClick={onToggle}
                />
              )}
            </div>
          </div>
        )}
      </nav>

      {/* Bottom */}
      <div
        className={[
          'border-t border-border space-y-0.5',
          collapsed ? 'p-2' : 'p-3',
        ].join(' ')}
      >
        <button
          onClick={onSettingsClick}
          onDoubleClick={onToggle}
          title={collapsed ? 'Settings' : undefined}
          className={[
            'group relative flex w-full items-center rounded-lg text-[13px] font-medium transition-all',
            collapsed ? 'justify-center px-0 py-2' : 'gap-3 px-3 py-2',
            'text-text-secondary hover:bg-sidebar-hover hover:text-text-primary',
          ].join(' ')}
        >
          <Settings size={18} strokeWidth={1.75} className="shrink-0" />
          {!collapsed && <span className="truncate">Settings</span>}
        </button>

        {/* User info + logout */}
        {user && (
          <div
            className={[
              'mt-1 flex items-center rounded-lg',
              collapsed ? 'justify-center py-2' : 'gap-2 px-3 py-2',
            ].join(' ')}
          >
            <div
              className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-accent-muted text-2xs font-semibold text-accent"
              title={
                collapsed
                  ? `${user.name}${user.permissionSetName ? ` (${user.permissionSetName})` : ''}`
                  : undefined
              }
            >
              {user.name.charAt(0).toUpperCase()}
            </div>
            {!collapsed && (
              <>
                <div className="min-w-0 flex-1">
                  <div className="truncate text-2xs font-medium text-text-primary">
                    {user.name}
                  </div>
                  <div className="truncate text-2xs text-text-tertiary">
                    {user.permissionSetName || user.email}
                  </div>
                </div>
                <button
                  onClick={handleLogout}
                  title="Sign out"
                  aria-label="Log out"
                  className="shrink-0 rounded p-1 text-text-tertiary transition-colors hover:bg-sidebar-hover hover:text-text-primary"
                >
                  <LogOut size={14} strokeWidth={1.75} />
                </button>
              </>
            )}
          </div>
        )}
      </div>
    </aside>
  );
}
