// apps/frontend/app/src/lib/components/ui/confirm-delete-dialog.svelte
<script lang="ts">
  import { AlertTriangle, X } from 'lucide-svelte';

  let {
    open,
    entityType,
    entityName,
    onConfirm,
    onCancel
  }: {
    open: boolean;
    entityType: string;
    entityName: string;
    onConfirm: () => void;
    onCancel: () => void;
  } = $props();

  let confirmText = $state('');

  const canConfirm = $derived(confirmText === entityName);

  $effect(() => {
    if (!open) confirmText = '';
  });

  function handleConfirm(): void {
    if (canConfirm) {
      onConfirm();
      confirmText = '';
    }
  }

  function handleCancel(): void {
    confirmText = '';
    onCancel();
  }

  function handleKeydown(e: KeyboardEvent): void {
    if (e.key === 'Escape') {
      handleCancel();
    } else if (e.key === 'Enter' && canConfirm) {
      handleConfirm();
    }
  }
</script>

{#if open}
  <!-- Overlay -->
  <div
    class="fixed inset-0 z-modal-backdrop bg-overlay animate-overlay-in"
    onclick={handleCancel}
    onkeydown={handleKeydown}
    role="presentation"
    tabindex="-1"
  ></div>

  <!-- Dialog -->
  <div class="fixed inset-0 z-modal flex items-center justify-center p-4">
    <div
      class="w-full max-w-md animate-modal-in rounded-xl border border-border bg-surface-1 shadow-xl"
      role="dialog"
      aria-modal="true"
      aria-labelledby="delete-dialog-title"
    >
      <div class="flex items-center justify-between border-b border-border px-5 py-4">
        <div class="flex items-center gap-3">
          <div class="flex h-9 w-9 items-center justify-center rounded-lg bg-error-muted">
            <AlertTriangle size={20} class="text-error" strokeWidth={1.75} />
          </div>
          <h2 id="delete-dialog-title" class="text-sm font-semibold text-text-primary">
            Delete {entityType}
          </h2>
        </div>
        <button
          onclick={handleCancel}
          class="flex h-8 w-8 items-center justify-center rounded-lg text-text-tertiary hover:bg-surface-2 hover:text-text-primary"
          title="Cancel"
          aria-label="Cancel deletion"
        >
          <X size={20} strokeWidth={1.75} />
        </button>
      </div>

      <div class="p-5">
        <p class="mb-4 text-sm text-text-secondary">
          This action cannot be undone. This will permanently delete the {entityType}
          <strong class="text-text-primary">{entityName}</strong> and all associated data.
        </p>

        <label for="confirm-delete-input" class="mb-1 block text-2xs font-medium text-text-tertiary">
          Type <span class="font-mono text-text-primary">{entityName}</span> to confirm
        </label>
        <!-- svelte-ignore a11y_autofocus -->
        <input
          id="confirm-delete-input"
          type="text"
          bind:value={confirmText}
          onkeydown={handleKeydown}
          placeholder={entityName}
          class="w-full rounded-lg border border-border bg-surface-0 px-3 py-2 text-sm text-text-primary placeholder:text-text-tertiary focus:border-accent focus:outline-none"
          autofocus
        />
      </div>

      <div class="flex justify-end gap-2 border-t border-border px-5 py-4">
        <button
          onclick={handleCancel}
          class="rounded-lg px-4 py-2 text-sm font-medium text-text-secondary hover:bg-surface-2"
        >
          Cancel
        </button>
        <button
          onclick={handleConfirm}
          disabled={!canConfirm}
          class="rounded-lg bg-error px-4 py-2 text-sm font-medium text-white hover:bg-error-hover disabled:cursor-not-allowed disabled:opacity-50"
        >
          Delete
        </button>
      </div>
    </div>
  </div>
{/if}

// apps/frontend/concord-app/src/app/components/ui/confirm-delete-dialog.tsx
import { useState, useEffect, useRef } from 'react';
import { AlertTriangle, X } from 'lucide-react';

interface ConfirmDeleteDialogProps {
  open: boolean;
  entityType: string;
  entityName: string;
  onConfirm: () => void;
  onCancel: () => void;
}

export function ConfirmDeleteDialog({
  open,
  entityType,
  entityName,
  onConfirm,
  onCancel,
}: ConfirmDeleteDialogProps) {
  const [inputValue, setInputValue] = useState('');
  const inputRef = useRef<HTMLInputElement>(null);

  const matches = inputValue === entityName;

  useEffect(() => {
    if (open) {
      setInputValue('');
      setTimeout(() => inputRef.current?.focus(), 50);
    }
  }, [open]);

  // Close on Escape
  useEffect(() => {
    if (!open) return;
    const handler = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onCancel();
    };
    window.addEventListener('keydown', handler);
    return () => window.removeEventListener('keydown', handler);
  }, [open, onCancel]);

  if (!open) return null;

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (matches) onConfirm();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center">
      {/* Backdrop */}
      <div
        className="absolute inset-0 bg-black/50"
        onClick={onCancel}
      />

      {/* Dialog */}
      <form
        onSubmit={handleSubmit}
        className="relative w-full max-w-md rounded-xl border border-border bg-surface-1 p-6 shadow-xl animate-fade-in"
      >
        <button
          type="button"
          onClick={onCancel}
          className="absolute right-4 top-4 rounded-lg p-1 text-text-tertiary transition-colors hover:bg-surface-2 hover:text-text-primary"
        >
          <X size={16} />
        </button>

        <div className="mb-4 flex items-center gap-3">
          <div className="flex h-10 w-10 items-center justify-center rounded-full bg-error-muted">
            <AlertTriangle size={20} className="text-error" />
          </div>
          <div>
            <h3 className="text-sm font-semibold text-text-primary">
              Delete {entityType}
            </h3>
            <p className="text-2xs text-text-tertiary">
              This action cannot be undone.
            </p>
          </div>
        </div>

        <p className="mb-4 text-sm text-text-secondary">
          To confirm, type{' '}
          <span className="font-semibold text-text-primary">{entityName}</span>{' '}
          below:
        </p>

        <input
          ref={inputRef}
          type="text"
          value={inputValue}
          onChange={(e) => setInputValue(e.target.value)}
          placeholder={entityName}
          className="mb-4 w-full rounded-lg border border-border bg-surface-0 px-3 py-2 text-sm text-text-primary placeholder:text-text-tertiary focus:border-accent focus:outline-none"
          autoComplete="off"
          spellCheck={false}
        />

        <div className="flex items-center justify-end gap-2">
          <button
            type="button"
            onClick={onCancel}
            className="rounded-lg px-4 py-2 text-sm font-medium text-text-secondary transition-colors hover:bg-surface-2"
          >
            Cancel
          </button>
          <button
            type="submit"
            disabled={!matches}
            className="rounded-lg bg-error px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-red-600 disabled:cursor-not-allowed disabled:opacity-40"
          >
            Delete
          </button>
        </div>
      </form>
    </div>
  );
}
