// apps/frontend/concord-app-svelte/src/lib/components/ui/status-badge.svelte
<script lang="ts">
  const COLORS: Record<string, string> = {
    // Existing
    ACTIVE: 'bg-success-muted text-success',
    DEPRECATED: 'bg-warning-muted text-warning',
    EOL: 'bg-error-muted text-error',
    DRAFT: 'bg-accent-muted text-accent',
    RELEASED: 'bg-success-muted text-success',
    UPLOAD: 'bg-accent-muted text-accent',
    EXTERNAL: 'bg-surface-2 text-text-secondary',
    // Node statuses
    ONLINE: 'bg-success-muted text-success',
    OFFLINE: 'bg-surface-2 text-text-tertiary',
    MAINTENANCE: 'bg-warning-muted text-warning',
    ERROR: 'bg-error-muted text-error',
    // Deployment statuses
    PENDING: 'bg-warning-muted text-warning',
    RUNNING: 'bg-success-muted text-success',
    STOPPED: 'bg-surface-2 text-text-secondary',
    FAILED: 'bg-error-muted text-error',
    // Type badges
    MANUFACTURING: 'bg-accent-muted text-accent',
    VALIDATION: 'bg-info-muted text-info',
    // Health statuses
    HEALTHY: 'bg-success-muted text-success',
    DEGRADED: 'bg-warning-muted text-warning',
    UNASSIGNED: 'bg-surface-2 text-text-tertiary',
    EMPTY: 'bg-surface-2 text-text-tertiary',
    UNKNOWN: 'bg-surface-2 text-text-tertiary',
  };

  let { status }: { status: string } = $props();

  const colorClass = $derived(COLORS[status] || 'bg-surface-2 text-text-secondary');
</script>

<span class="inline-flex items-center rounded-full px-2 py-0.5 text-2xs font-medium {colorClass}">
  {status}
</span>

// apps/frontend/concord-app/src/app/components/ui/status-badge.tsx
const COLORS: Record<string, string> = {
  ACTIVE: 'bg-success-muted text-success',
  DEPRECATED: 'bg-warning-muted text-warning',
  EOL: 'bg-error-muted text-error',
  DRAFT: 'bg-accent-muted text-accent',
  RELEASED: 'bg-success-muted text-success',
  UPLOAD: 'bg-accent-muted text-accent',
  EXTERNAL: 'bg-surface-2 text-text-secondary',
};

export function StatusBadge({ status }: { status: string }) {
  const colorClass = COLORS[status] || 'bg-surface-2 text-text-secondary';
  return (
    <span
      className={`inline-flex items-center rounded-full px-2 py-0.5 text-2xs font-medium ${colorClass}`}
    >
      {status}
    </span>
  );
}
