// apps/frontend/concord-app/src/app/components/system/action-button.tsx
import { useState } from 'react';
import { type LucideIcon } from 'lucide-react';

interface ActionButtonProps {
  label: string;
  icon: LucideIcon;
  variant: 'danger' | 'warning' | 'primary';
  confirmMessage: string;
  onConfirm: () => Promise<void>;
  onError?: (err: Error) => void;
  disabled?: boolean;
}

const variantStyles = {
  danger: 'bg-error text-white hover:bg-error-hover',
  warning: 'bg-warning text-white hover:bg-warning-hover',
  primary: 'bg-accent text-white hover:bg-accent-hover',
};

export function ActionButton({
  label,
  icon: Icon,
  variant,
  confirmMessage,
  onConfirm,
  onError,
  disabled = false,
}: ActionButtonProps) {
  const [confirming, setConfirming] = useState(false);
  const [loading, setLoading] = useState(false);
  const [actionError, setActionError] = useState<string | null>(null);

  const handleClick = () => {
    if (!confirming) {
      setConfirming(true);
      setActionError(null);
      return;
    }
    setLoading(true);
    setActionError(null);
    onConfirm()
      .then(() => setConfirming(false))
      .catch((err) => {
        const message = err instanceof Error ? err.message : 'Action failed';
        setActionError(message);
        setConfirming(false);
        onError?.(err instanceof Error ? err : new Error(message));
      })
      .finally(() => setLoading(false));
  };

  const handleCancel = () => {
    setConfirming(false);
  };

  if (confirming) {
    return (
      <div className="flex items-center gap-2">
        {actionError && <span className="text-xs text-error">{actionError}</span>}
        <span className="text-xs text-text-secondary">{confirmMessage}</span>
        <button
          onClick={handleClick}
          disabled={loading}
          className={`rounded px-3 py-1.5 text-xs font-medium transition-colors ${variantStyles[variant]} ${
            loading ? 'opacity-50' : ''
          }`}
        >
          {loading ? 'Working...' : 'Confirm'}
        </button>
        <button
          onClick={handleCancel}
          disabled={loading}
          className="rounded px-3 py-1.5 text-xs font-medium text-text-tertiary transition-colors hover:text-text-primary"
        >
          Cancel
        </button>
      </div>
    );
  }

  return (
    <button
      onClick={handleClick}
      disabled={disabled}
      className={`flex items-center gap-1.5 rounded px-3 py-1.5 text-xs font-medium transition-colors ${
        variantStyles[variant]
      } ${disabled ? 'opacity-50 cursor-not-allowed' : ''}`}
    >
      <Icon size={12} />
      {label}
    </button>
  );
}

// research/embedded/concord/apps/frontend/app/src/lib/components/system/action-button.svelte
<script lang="ts">
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  type IconComponent = any;

  type VariantType = 'danger' | 'warning' | 'primary';

  interface Props {
    label: string;
    icon: IconComponent;
    variant: VariantType;
    confirmMessage: string;
    onConfirm: () => Promise<void>;
    onError?: (err: Error) => void;
    disabled?: boolean;
  }

  let { label, icon, variant, confirmMessage, onConfirm, onError, disabled = false }: Props = $props();

  let confirming = $state(false);
  let loading = $state(false);
  let error = $state<string | null>(null);

  const buttonClass = $derived.by(() => {
    switch (variant) {
      case 'danger':
        return 'bg-error/10 text-error hover:bg-error/20';
      case 'warning':
        return 'bg-warning/10 text-warning hover:bg-warning/20';
      default:
        return 'bg-accent/10 text-accent hover:bg-accent/20';
    }
  });

  async function handleConfirm() {
    loading = true;
    error = null;
    try {
      await onConfirm();
      confirming = false;
    } catch (e) {
      const err = e instanceof Error ? e : new Error('Unknown error');
      error = err.message;
      onError?.(err);
    } finally {
      loading = false;
    }
  }

  function handleCancel() {
    confirming = false;
    error = null;
  }
</script>

{#if confirming}
  <div class="flex items-center gap-2">
    <span class="text-xs text-text-secondary">{confirmMessage}</span>
    <button
      onclick={handleConfirm}
      disabled={loading}
      class="px-2 py-1 text-xs font-medium rounded bg-error text-white hover:bg-error/90 disabled:opacity-50"
    >
      {loading ? 'Working...' : 'Confirm'}
    </button>
    <button
      onclick={handleCancel}
      disabled={loading}
      class="px-2 py-1 text-xs font-medium rounded bg-surface-2 text-text-secondary hover:bg-surface-2/80"
    >
      Cancel
    </button>
  </div>
{:else}
  <button
    onclick={() => confirming = true}
    {disabled}
    class="flex items-center gap-1.5 px-2 py-1 text-xs font-medium rounded {buttonClass} disabled:opacity-50"
  >
{#if icon}{@const Icon = icon}<Icon class="w-4 h-4" />{/if}
    {label}
  </button>
{/if}

{#if error}
  <span class="text-xs text-error ml-2">{error}</span>
{/if}
