// apps/frontend/concord-app/src/app/components/system/status-indicator.tsx
const STATUS_MAP: Record<string, { color: string; bg: string }> = {
  Ready: { color: 'bg-success', bg: 'bg-success-muted' },
  Running: { color: 'bg-success', bg: 'bg-success-muted' },
  Active: { color: 'bg-success', bg: 'bg-success-muted' },
  Succeeded: { color: 'bg-success', bg: 'bg-success-muted' },
  Pending: { color: 'bg-warning', bg: 'bg-warning-muted' },
  NotReady: { color: 'bg-error', bg: 'bg-error-muted' },
  Failed: { color: 'bg-error', bg: 'bg-error-muted' },
  Error: { color: 'bg-error', bg: 'bg-error-muted' },
  Unknown: { color: 'bg-text-tertiary', bg: 'bg-surface-2' },
  Warning: { color: 'bg-warning', bg: 'bg-warning-muted' },
  Normal: { color: 'bg-success', bg: 'bg-success-muted' },
};

export function StatusIndicator({ status }: { status: string }) {
  const style = STATUS_MAP[status] || STATUS_MAP.Unknown;

  return (
    <span className={`inline-flex items-center gap-1.5 rounded-full px-2 py-0.5 text-xs font-medium ${style.bg}`}>
      <span className={`inline-block h-1.5 w-1.5 rounded-full ${style.color}`} />
      {status}
    </span>
  );
}

// research/embedded/concord/apps/frontend/app/src/lib/components/system/status-indicator.svelte
<script lang="ts">
  type StatusType = 'Ready' | 'Running' | 'Active' | 'Succeeded' | 'Complete' |
                    'Pending' | 'ContainerCreating' | 'Terminating' |
                    'NotReady' | 'Failed' | 'Error' | 'CrashLoopBackOff' |
                    'Warning' | 'Normal' | 'Unknown' | string;

  interface Props {
    status: StatusType;
  }

  let { status }: Props = $props();

  const statusColors = $derived.by(() => {
    switch (status) {
      case 'Ready':
      case 'Running':
      case 'Active':
      case 'Succeeded':
      case 'Complete':
      case 'Normal':
        return { dot: 'bg-success', bg: 'bg-success/10', text: 'text-success' };
      case 'Pending':
      case 'ContainerCreating':
      case 'Terminating':
      case 'Warning':
        return { dot: 'bg-warning', bg: 'bg-warning/10', text: 'text-warning' };
      case 'NotReady':
      case 'Failed':
      case 'Error':
      case 'CrashLoopBackOff':
        return { dot: 'bg-error', bg: 'bg-error/10', text: 'text-error' };
      default:
        return { dot: 'bg-text-tertiary', bg: 'bg-surface-2', text: 'text-text-tertiary' };
    }
  });
</script>

<span class="inline-flex items-center gap-1.5 px-2 py-0.5 rounded-full text-xs font-medium {statusColors.bg} {statusColors.text}">
  <span class="w-1.5 h-1.5 rounded-full {statusColors.dot}"></span>
  {status}
</span>
