// apps/frontend/concord-app/src/app/components/system/usage-bar.tsx
interface UsageBarProps {
  label: string;
  used: number;
  total: number;
  unit?: string;
  formatFn?: (val: number) => string;
}

function defaultFormat(val: number): string {
  return val.toLocaleString();
}

function getBarColor(pct: number): string {
  if (pct >= 90) return 'bg-error';
  if (pct >= 70) return 'bg-warning';
  return 'bg-success';
}

export function UsageBar({ label, used, total, unit = '', formatFn = defaultFormat }: UsageBarProps) {
  const pct = total > 0 ? Math.min((used / total) * 100, 100) : 0;

  return (
    <div>
      <div className="mb-1.5 flex items-baseline justify-between">
        <span className="text-xs font-medium text-text-secondary">{label}</span>
        <span className="text-xs tabular-nums text-text-tertiary">
          {formatFn(used)}{unit} / {formatFn(total)}{unit}
          <span className="ml-1.5 font-medium text-text-secondary">({pct.toFixed(0)}%)</span>
        </span>
      </div>
      <div className="h-2 w-full overflow-hidden rounded-full bg-surface-3">
        <div
          className={`h-full rounded-full transition-all duration-700 ease-out ${getBarColor(pct)}`}
          style={{ width: `${pct}%` }}
        />
      </div>
    </div>
  );
}

// research/embedded/concord/apps/frontend/app/src/lib/components/system/usage-bar.svelte
<script lang="ts">
  interface Props {
    label: string;
    used: number;
    total: number;
    unit?: string;
    formatFn?: (val: number) => string;
  }

  let { label, used, total, unit = '', formatFn }: Props = $props();

  const percentage = $derived(total > 0 ? Math.min((used / total) * 100, 100) : 0);

  const colorClass = $derived.by(() => {
    if (percentage >= 90) return 'bg-error';
    if (percentage >= 70) return 'bg-warning';
    return 'bg-success';
  });

  const formatValue = (val: number) => {
    if (formatFn) return formatFn(val);
    return unit ? `${val}${unit}` : val.toString();
  };
</script>

<div class="space-y-1">
  <div class="flex justify-between text-xs">
    <span class="text-text-secondary">{label}</span>
    <span class="text-text-primary font-medium">
      {formatValue(used)} / {formatValue(total)} ({Math.round(percentage)}%)
    </span>
  </div>
  <div class="h-2 bg-surface-2 rounded-full overflow-hidden">
    <div
      class="h-full {colorClass} transition-all duration-500 ease-out rounded-full"
      style="width: {percentage}%"
    ></div>
  </div>
</div>
