// apps/frontend/concord-app-svelte/src/lib/components/ui/artifact-upload.svelte
<script lang="ts">
  import { Upload } from 'lucide-svelte';

  interface Props {
    onUpload: (file: File) => Promise<void>;
    disabled?: boolean;
  }

  let { onUpload, disabled = false }: Props = $props();

  let dragOver = $state(false);
  let uploading = $state(false);

  async function handleFile(file: File) {
    uploading = true;
    try {
      await onUpload(file);
    } finally {
      uploading = false;
    }
  }

  function handleDrop(e: DragEvent) {
    e.preventDefault();
    dragOver = false;
    const file = e.dataTransfer?.files[0];
    if (file) handleFile(file);
  }

  function handleChange(e: Event) {
    const input = e.target as HTMLInputElement;
    const file = input.files?.[0];
    if (file) handleFile(file);
    input.value = '';
  }
</script>

<div
  role="button"
  tabindex="0"
  ondragover={(e) => { e.preventDefault(); dragOver = true; }}
  ondragleave={() => (dragOver = false)}
  ondrop={handleDrop}
  class={[
    'flex flex-col items-center justify-center rounded-lg border-2 border-dashed p-4 transition-colors',
    dragOver
      ? 'border-accent bg-accent-muted'
      : 'border-border bg-surface-0 hover:border-text-tertiary',
    disabled ? 'pointer-events-none opacity-50' : 'cursor-pointer'
  ].join(' ')}
>
  <label class="flex cursor-pointer flex-col items-center gap-2">
    <input
      type="file"
      onchange={handleChange}
      class="hidden"
      disabled={disabled || uploading}
    />
    <Upload
      size={20}
      class="text-text-tertiary"
      strokeWidth={1.5}
    />
    <span class="text-2xs text-text-tertiary">
      {uploading ? 'Uploading...' : 'Drop file or click to upload'}
    </span>
  </label>
</div>

// apps/frontend/concord-app/src/app/pages/codebases/artifact-upload.tsx
import { useCallback, useState } from 'react';
import { Upload } from 'lucide-react';

interface ArtifactUploadProps {
  onUpload: (file: File) => Promise<void>;
  disabled?: boolean;
}

export function ArtifactUpload({ onUpload, disabled }: ArtifactUploadProps) {
  const [dragOver, setDragOver] = useState(false);
  const [uploading, setUploading] = useState(false);

  const handleFile = useCallback(
    async (file: File) => {
      setUploading(true);
      try {
        await onUpload(file);
      } finally {
        setUploading(false);
      }
    },
    [onUpload]
  );

  const handleDrop = useCallback(
    (e: React.DragEvent) => {
      e.preventDefault();
      setDragOver(false);
      const file = e.dataTransfer.files[0];
      if (file) handleFile(file);
    },
    [handleFile]
  );

  const handleChange = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => {
      const file = e.target.files?.[0];
      if (file) handleFile(file);
      // Reset the input so the same file can be selected again
      e.target.value = '';
    },
    [handleFile]
  );

  return (
    <div
      onDragOver={(e) => {
        e.preventDefault();
        setDragOver(true);
      }}
      onDragLeave={() => setDragOver(false)}
      onDrop={handleDrop}
      className={[
        'flex flex-col items-center justify-center rounded-lg border-2 border-dashed p-4 transition-colors',
        dragOver
          ? 'border-accent bg-accent-muted'
          : 'border-border bg-surface-0 hover:border-text-tertiary',
        disabled ? 'pointer-events-none opacity-50' : 'cursor-pointer',
      ].join(' ')}
    >
      <label className="flex cursor-pointer flex-col items-center gap-2">
        <input
          type="file"
          onChange={handleChange}
          className="hidden"
          disabled={disabled || uploading}
        />
        <Upload
          size={20}
          className="text-text-tertiary"
          strokeWidth={1.5}
        />
        <span className="text-2xs text-text-tertiary">
          {uploading ? 'Uploading...' : 'Drop file or click to upload'}
        </span>
      </label>
    </div>
  );
}
