// apps/frontend/concord-app/src/app/components/system/label-list.tsx
interface LabelListProps {
  labels: Record<string, string>;
  truncateAt?: number;
}

export function LabelList({ labels, truncateAt = 40 }: LabelListProps) {
  const entries = Object.entries(labels);
  if (entries.length === 0) return null;

  return (
    <div className="flex flex-wrap gap-1.5">
      {entries.map(([k, v]) => (
        <span
          key={k}
          className="rounded bg-surface-2 px-2 py-0.5 font-mono text-2xs text-text-secondary"
          title={`${k}=${v}`}
        >
          {k.length > truncateAt ? `...${k.slice(-(truncateAt - 3))}` : k}={v}
        </span>
      ))}
    </div>
  );
}

// apps/frontend/app/src/lib/components/system/label-list.svelte
<script lang="ts">
  interface Props {
    labels: Record<string, string>;
    truncateAt?: number;
  }

  let { labels, truncateAt = 30 }: Props = $props();

  const entries = $derived(Object.entries(labels));

  function truncate(text: string, max: number): string {
    return text.length > max ? text.slice(0, max) + '...' : text;
  }
</script>

{#if entries.length === 0}
  <span class="text-xs text-text-tertiary">No labels</span>
{:else}
  <div class="flex flex-wrap gap-1">
    {#each entries as [key, value]}
      {@const full = `${key}=${value}`}
      <span
        class="inline-flex items-center px-1.5 py-0.5 rounded text-2xs bg-surface-2 text-text-secondary font-mono"
        title={full}
      >
        {truncate(key, truncateAt)}={truncate(value, truncateAt)}
      </span>
    {/each}
  </div>
{/if}
