// apps/frontend/concord-app/src/app/pages/products/board-revision-list.tsx
import { useState } from 'react';
import { Plus, X, Check, Pencil, Trash2 } from 'lucide-react';
import { Select } from '../../components/ui/select';
import { api } from '../../api';
import { StatusBadge } from '../../components/ui/status-badge';
import { ErrorAlert } from '../../components/ui/error-alert';
import { ConfirmDeleteDialog } from '../../components/ui/confirm-delete-dialog';
import { ApiResponse } from '../../types';
import { BoardRevision } from '../../types/models';

function ChipsetTagInput({
  value,
  onChange,
  supportedSocs,
}: {
  value: string[];
  onChange: (chipsets: string[]) => void;
  supportedSocs: string[];
}) {
  const available = supportedSocs.filter((s) => !value.includes(s));

  const removeChipset = (chip: string) => {
    onChange(value.filter((c) => c !== chip));
  };

  return (
    <div className="flex min-h-[38px] flex-wrap items-center gap-1.5 rounded-lg border border-border bg-surface-0 px-2.5 py-1.5 focus-within:border-accent">
      {value.map((chip) => (
        <span
          key={chip}
          className="inline-flex items-center gap-1 rounded bg-accent/10 px-1.5 py-0.5 text-2xs font-medium text-accent"
        >
          {chip}
          <button
            type="button"
            onClick={() => removeChipset(chip)}
            aria-label="Remove chipset"
            className="ml-0.5 rounded-full p-0.5 hover:bg-accent/20"
          >
            <X size={10} />
          </button>
        </span>
      ))}
      {available.length > 0 && (
        <Select
          compact
          value=""
          onChange={(e) => {
            if (e.target.value) onChange([...value, e.target.value]);
          }}
          className="min-w-[100px] flex-1"
        >
          <option value="">{value.length === 0 ? 'Select SoCs...' : 'Add another...'}</option>
          {available.map((s) => (
            <option key={s} value={s}>{s}</option>
          ))}
        </Select>
      )}
    </div>
  );
}

export function BoardRevisionList({
  productId,
  revisions,
  supportedSocs,
  canManage,
  onRefresh,
}: {
  productId: string;
  revisions: BoardRevision[];
  supportedSocs: string[];
  canManage: boolean;
  onRefresh: () => void;
}) {
  const [error, setError] = useState<string | null>(null);
  const [showForm, setShowForm] = useState(false);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [submitting, setSubmitting] = useState(false);
  const [formVersion, setFormVersion] = useState('');
  const [formChipsets, setFormChipsets] = useState<string[]>([]);
  const [formStatus, setFormStatus] = useState('ACTIVE');
  const [formNotes, setFormNotes] = useState('');
  const [deleteTarget, setDeleteTarget] = useState<{ id: string; name: string } | null>(null);

  const resetForm = () => {
    setFormVersion('');
    setFormChipsets([]);
    setFormStatus('ACTIVE');
    setFormNotes('');
    setEditingId(null);
    setShowForm(false);
  };

  const startEdit = (r: BoardRevision) => {
    setFormVersion(r.version);
    setFormChipsets(r.chipsets || []);
    setFormStatus(r.status);
    setFormNotes(r.notes || '');
    setEditingId(r.id);
    setShowForm(true);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);
    setSubmitting(true);

    const body = {
      version: formVersion,
      chipsets: formChipsets,
      status: formStatus,
      notes: formNotes || null,
    };

    try {
      if (editingId) {
        await api(`/v2/products/${productId}/board-revisions/${editingId}`, {
          method: 'PUT',
          body: JSON.stringify(body),
        });
      } else {
        await api(`/v2/products/${productId}/board-revisions`, {
          method: 'POST',
          body: JSON.stringify(body),
        });
      }
      resetForm();
      onRefresh();
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : 'Failed to save board revision');
    } finally {
      setSubmitting(false);
    }
  };

  const handleDelete = async (id: string) => {
    setError(null);
    try {
      await api(`/v2/products/${productId}/board-revisions/${id}`, { method: 'DELETE' });
      onRefresh();
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : 'Failed to delete');
    }
  };

  return (
    <div>
      <div className="mb-3 flex items-center justify-between">
        <h3 className="text-sm font-semibold text-text-primary">Board Revisions</h3>
        {canManage && !showForm && (
          <button
            onClick={() => { resetForm(); setShowForm(true); }}
            className="flex items-center gap-1.5 rounded-lg bg-accent px-2.5 py-1.5 text-2xs font-medium text-white hover:bg-accent-hover"
          >
            <Plus size={13} />
            Add revision
          </button>
        )}
      </div>

      <ErrorAlert message={error} />

      {showForm && (
        <div className="mb-4 rounded-lg border border-border bg-surface-0 p-4">
          <div className="mb-3 flex items-center justify-between">
            <span className="text-2xs font-medium text-text-secondary">
              {editingId ? 'Edit revision' : 'New revision'}
            </span>
            <button onClick={resetForm} className="rounded p-1 text-text-tertiary hover:bg-surface-2 hover:text-text-primary">
              <X size={14} />
            </button>
          </div>
          <form onSubmit={handleSubmit}>
            <div className="mb-3 grid grid-cols-2 gap-3">
              <div>
                <label className="mb-1 block text-2xs font-medium text-text-tertiary">Version</label>
                <input
                  type="text"
                  required
                  value={formVersion}
                  onChange={(e) => setFormVersion(e.target.value)}
                  placeholder="e.g. A0, B1"
                  className="w-full rounded-lg border border-border bg-surface-0 px-3 py-2 text-sm text-text-primary placeholder:text-text-tertiary focus:border-accent focus:outline-none"
                />
              </div>
              <div>
                <label className="mb-1 block text-2xs font-medium text-text-tertiary">Status</label>
                <Select
                  value={formStatus}
                  onChange={(e) => setFormStatus(e.target.value)}
                >
                  <option value="ACTIVE">Active</option>
                  <option value="DEPRECATED">Deprecated</option>
                  <option value="EOL">EOL</option>
                </Select>
              </div>
            </div>
            <div className="mb-3">
              <label className="mb-1 block text-2xs font-medium text-text-tertiary">
                Chipsets
                <span className="ml-1 font-normal text-text-tertiary/70">— press Enter or comma to add</span>
              </label>
              <ChipsetTagInput value={formChipsets} onChange={setFormChipsets} supportedSocs={supportedSocs} />
            </div>
            <div className="mb-3">
              <label className="mb-1 block text-2xs font-medium text-text-tertiary">Notes</label>
              <input
                type="text"
                value={formNotes}
                onChange={(e) => setFormNotes(e.target.value)}
                placeholder="Optional notes"
                className="w-full rounded-lg border border-border bg-surface-0 px-3 py-2 text-sm text-text-primary placeholder:text-text-tertiary focus:border-accent focus:outline-none"
              />
            </div>
            <div className="flex gap-2">
              <button type="submit" disabled={submitting} className="flex items-center gap-1.5 rounded-lg bg-accent px-3 py-1.5 text-2xs font-medium text-white hover:bg-accent-hover disabled:opacity-50">
                <Check size={12} />
                {submitting ? 'Saving...' : editingId ? 'Save' : 'Create'}
              </button>
              <button type="button" onClick={resetForm} className="rounded-lg px-3 py-1.5 text-2xs font-medium text-text-secondary hover:bg-surface-2">
                Cancel
              </button>
            </div>
          </form>
        </div>
      )}

      {revisions.length > 0 ? (
        <div className="overflow-hidden rounded-lg border border-border">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-border bg-surface-2">
                <th className="px-3 py-2 text-left text-2xs font-medium text-text-tertiary">Version</th>
                <th className="px-3 py-2 text-left text-2xs font-medium text-text-tertiary">Chipsets</th>
                <th className="px-3 py-2 text-left text-2xs font-medium text-text-tertiary">Status</th>
                <th className="px-3 py-2 text-left text-2xs font-medium text-text-tertiary">Notes</th>
                {canManage && <th className="px-3 py-2 text-right text-2xs font-medium text-text-tertiary">Actions</th>}
              </tr>
            </thead>
            <tbody>
              {revisions.map((r) => (
                <tr key={r.id} className="border-b border-border-subtle last:border-0 hover:bg-surface-1">
                  <td className="px-3 py-2 font-medium text-text-primary">{r.version}</td>
                  <td className="px-3 py-2">
                    {r.chipsets.length > 0 ? (
                      <div className="flex flex-wrap gap-1">
                        {r.chipsets.map((c) => (
                          <span key={c} className="rounded bg-accent/10 px-1.5 py-0.5 text-2xs font-medium text-accent">
                            {c}
                          </span>
                        ))}
                      </div>
                    ) : (
                      <span className="text-text-tertiary">—</span>
                    )}
                  </td>
                  <td className="px-3 py-2"><StatusBadge status={r.status} /></td>
                  <td className="px-3 py-2 text-text-tertiary">{r.notes || '—'}</td>
                  {canManage && (
                    <td className="px-3 py-2 text-right">
                      <div className="flex justify-end gap-1">
                        <button
                          onClick={() => startEdit(r)}
                          className="rounded p-1 text-text-tertiary hover:bg-surface-2 hover:text-text-primary"
                          title="Edit"
                          aria-label="Edit"
                        >
                          <Pencil size={13} />
                        </button>
                        <button
                          onClick={() => setDeleteTarget({ id: r.id, name: r.version })}
                          className="rounded p-1 text-text-tertiary hover:bg-error-muted hover:text-error"
                          title="Delete"
                          aria-label="Delete"
                        >
                          <Trash2 size={13} />
                        </button>
                      </div>
                    </td>
                  )}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      ) : (
        <div className="py-6 text-center text-sm text-text-tertiary">
          No board revisions yet
        </div>
      )}

      <ConfirmDeleteDialog
        open={!!deleteTarget}
        entityType="board revision"
        entityName={deleteTarget?.name || ''}
        onConfirm={() => { handleDelete(deleteTarget!.id); setDeleteTarget(null); }}
        onCancel={() => setDeleteTarget(null)}
      />
    </div>
  );
}

// apps/frontend/concord-app-svelte/src/lib/components/catalog/board-revision-list.svelte
<script lang="ts">
  import { Plus, Check, X } from 'lucide-svelte';
  import { api } from '$lib/api';
  import StatusBadge from '$lib/components/ui/status-badge.svelte';
  import Select from '$lib/components/ui/select.svelte';
  import ConfirmDeleteDialog from '$lib/components/ui/confirm-delete-dialog.svelte';
  import ErrorAlert from '$lib/components/ui/error-alert.svelte';
  import ChipsetTagInput from './chipset-tag-input.svelte';
  import type { BoardRevision, FirmwareBuild, Chipset } from '$lib/types/models';

  interface Props {
    productId: string;
    boardId: string;
    revisions: BoardRevision[];
    builds: FirmwareBuild[];
    chipsets: Chipset[];
    canManage: boolean;
    onRefresh: () => void;
  }

  let { productId, boardId, revisions, builds, chipsets, canManage, onRefresh }: Props = $props();

  let error = $state<string | null>(null);
  let showForm = $state(false);
  let editingId = $state<string | null>(null);
  let submitting = $state(false);

  let formVersion = $state('');
  let formChipsetIds = $state<string[]>([]);
  let formStatus = $state('ACTIVE');
  let formSelectedBuilds = $state<Record<string, string>>({});
  let formNotes = $state('');

  let deleteTarget = $state<{ id: string; name: string } | null>(null);

  /** Chipset options for the tag input */
  const chipsetOptions = $derived(
    chipsets.map((c) => ({ id: c.id, name: c.name }))
  );

  /** Get chipset name by ID */
  function chipsetName(id: string): string {
    return chipsets.find((c) => c.id === id)?.name || id;
  }

  /** Check if a chipset is a modem by ID */
  function isModemChipset(id: string): boolean {
    return chipsets.find((c) => c.id === id)?.isModem ?? false;
  }

  /** Get firmware build options filtered to a specific chipset ID */
  function buildsForChipset(chipsetId: string) {
    return builds
      .filter((b) => b.chipsetId === chipsetId)
      .map((b) => {
        let label = `${b.version}`;
        if (b.modemFilename) label += ' + modem';
        return { value: b.id, label };
      });
  }

  /** Look up a build by ID */
  function getBuild(buildId: string): FirmwareBuild | undefined {
    return builds.find((b) => b.id === buildId);
  }

  function resetForm() {
    formVersion = '';
    formChipsetIds = [];
    formStatus = 'ACTIVE';
    formSelectedBuilds = {};
    formNotes = '';
    editingId = null;
    showForm = false;
  }

  function startEdit(rev: BoardRevision) {
    formVersion = rev.version;
    formChipsetIds = rev.chipsets.map((c) => c.id);
    formStatus = rev.status;
    formSelectedBuilds = { ...(rev.selectedBuilds || {}) };
    formNotes = rev.notes || '';
    editingId = rev.id;
    showForm = true;
  }

  async function handleSubmit(e: Event) {
    e.preventDefault();
    error = null;

    // Validate: each chipset must have a firmware build selected
    if (editingId && formChipsetIds.length > 0) {
      const missing = formChipsetIds.filter(
        (id) => buildsForChipset(id).length > 0 && !formSelectedBuilds[id]
      );
      if (missing.length > 0) {
        error = `Select firmware for: ${missing.map(chipsetName).join(', ')}`;
        return;
      }
    }

    submitting = true;

    const body: Record<string, unknown> = {
      version: formVersion,
      chipsetIds: formChipsetIds,
      status: formStatus,
      notes: formNotes || null,
    };
    if (editingId) {
      // Only include chipsets that have a selection
      const selected: Record<string, string> = {};
      for (const id of formChipsetIds) {
        if (formSelectedBuilds[id]) {
          selected[id] = formSelectedBuilds[id];
        }
      }
      body.selectedBuilds = Object.keys(selected).length > 0 ? selected : null;
    }

    try {
      if (editingId) {
        await api.put(`/v2/products/${productId}/boards/${boardId}/revisions/${editingId}`, body);
      } else {
        await api.post(`/v2/products/${productId}/boards/${boardId}/revisions`, body);
      }
      resetForm();
      onRefresh();
    } catch (err) {
      error = err instanceof Error ? err.message : 'Failed to save revision';
    } finally {
      submitting = false;
    }
  }

  function promptDelete(id: string) {
    const rev = revisions.find((r) => r.id === id);
    deleteTarget = { id, name: rev?.version || '' };
  }

  async function handleDelete(id: string) {
    error = null;
    try {
      await api.delete(`/v2/products/${productId}/boards/${boardId}/revisions/${id}`);
      onRefresh();
    } catch (err) {
      error = err instanceof Error ? err.message : 'Failed to delete revision';
    }
  }
</script>

<div>
  <ErrorAlert message={error} />

  <div class="mb-3 flex items-center justify-between">
    <h3 class="text-sm font-semibold text-text-primary">Board Revisions</h3>
    {#if canManage && !showForm}
      <button
        onclick={() => { resetForm(); showForm = true; }}
        class="flex items-center gap-1.5 rounded-lg bg-accent px-2.5 py-1.5 text-2xs font-medium text-white hover:bg-accent-hover"
      >
        <Plus size={16} />
        Add revision
      </button>
    {/if}
  </div>

  {#if showForm}
    <form
      onsubmit={handleSubmit}
      class="mb-4 rounded-lg border border-border bg-surface-0 p-3"
    >
      <div class="grid grid-cols-2 gap-3 sm:grid-cols-4">
        <label>
          <span class="mb-1 block text-2xs font-medium text-text-tertiary">Version</span>
          <input
            type="text"
            required
            bind:value={formVersion}
            placeholder="e.g. REV1.0"
            class="w-full rounded-lg border border-border bg-surface-1 px-3 py-2 text-sm text-text-primary placeholder:text-text-tertiary focus:border-accent focus:outline-none"
          />
        </label>
        <div>
          <span class="mb-1 block text-2xs font-medium text-text-tertiary">Chipsets</span>
          <ChipsetTagInput
            selected={formChipsetIds}
            options={chipsetOptions}
            onchange={(v) => (formChipsetIds = v)}
          />
        </div>
        <Select
          bind:value={formStatus}
          label="Status"
          options={[
            { value: 'ACTIVE', label: 'Active' },
            { value: 'DEPRECATED', label: 'Deprecated' },
            { value: 'EOL', label: 'End of Life' },
          ]}
        />
        <label>
          <span class="mb-1 block text-2xs font-medium text-text-tertiary">Notes</span>
          <input
            type="text"
            bind:value={formNotes}
            placeholder="Optional"
            class="w-full rounded-lg border border-border bg-surface-1 px-3 py-2 text-sm text-text-primary placeholder:text-text-tertiary focus:border-accent focus:outline-none"
          />
        </label>
      </div>

      <!-- Per-chipset firmware selection (edit mode only) -->
      {#if editingId && formChipsetIds.length > 0}
        {@const chipsWithBuilds = formChipsetIds.filter((id) => buildsForChipset(id).length > 0)}
        {#if chipsWithBuilds.length > 0}
          <div class="mt-3 border-t border-border-subtle pt-3">
            <span class="mb-2 block text-2xs font-semibold text-text-secondary">Selected Firmware per Chipset</span>
            <div class="grid grid-cols-1 gap-3 sm:grid-cols-2">
              {#each chipsWithBuilds as chipId}
                {@const isModem = isModemChipset(chipId)}
                {@const options = buildsForChipset(chipId)}
                {@const selectedBuild = formSelectedBuilds[chipId] ? getBuild(formSelectedBuilds[chipId]) : null}
                <div>
                  <Select
                    bind:value={formSelectedBuilds[chipId]}
                    label={isModem ? `${chipsetName(chipId)} (modem)` : chipsetName(chipId)}
                    placeholder="Select build..."
                    {options}
                  />
                  {#if isModem && selectedBuild && !selectedBuild.modemFilename}
                    <p class="mt-1 text-2xs text-warning">No modem firmware on this build — upload one in Firmware Releases.</p>
                  {/if}
                </div>
              {/each}
            </div>
          </div>
        {/if}
      {/if}

      <div class="mt-3 flex gap-2">
        <button
          type="submit"
          disabled={submitting}
          class="flex items-center gap-1.5 rounded-lg bg-accent px-3 py-1.5 text-xs font-medium text-white hover:bg-accent-hover disabled:opacity-50"
        >
          <Check size={16} />
          {submitting ? 'Saving...' : editingId ? 'Save' : 'Create'}
        </button>
        <button
          type="button"
          onclick={resetForm}
          class="rounded-lg px-3 py-1.5 text-xs font-medium text-text-secondary hover:bg-surface-2"
        >
          Cancel
        </button>
      </div>
    </form>
  {/if}

  {#if revisions.length > 0}
    <div class="table-wrapper">
      <table class="table">
        <thead>
          <tr class="border-b border-border">
            <th class="table-header">Version</th>
            <th class="table-header">Chipsets</th>
            <th class="table-header">Selected Firmware</th>
            <th class="table-header">Status</th>
            <th class="table-header">Notes</th>
            {#if canManage}
              <th class="table-header text-right">Actions</th>
            {/if}
          </tr>
        </thead>
        <tbody>
          {#each revisions as rev (rev.id)}
            <tr class="table-row">
              <td class="table-cell font-medium text-text-primary">{rev.version}</td>
              <td class="table-cell">
                <div class="flex flex-wrap gap-1">
                  {#each rev.chipsets as chip}
                    <span class="rounded-full bg-accent-muted px-2 py-0.5 text-2xs font-medium text-accent">
                      {chip.name}
                    </span>
                  {/each}
                </div>
              </td>
              <td class="table-cell">
                {#if rev.selectedBuilds && Object.keys(rev.selectedBuilds).length > 0}
                  <div class="flex flex-col gap-1">
                    {#each Object.entries(rev.selectedBuilds) as [chipId, buildId]}
                      {@const build = getBuild(buildId)}
                      {#if build}
                        <span class="inline-flex items-center gap-1 rounded-full bg-success-muted px-2 py-0.5 text-2xs font-medium text-success">
                          <span class="text-success/70">{chipsetName(chipId)}:</span>
                          {build.version}
                          {#if build.modemFilename}
                            <span class="rounded-full bg-surface-2 px-1.5 text-text-secondary">modem</span>
                          {/if}
                        </span>
                      {/if}
                    {/each}
                  </div>
                {:else}
                  <span class="text-2xs text-text-tertiary">-</span>
                {/if}
              </td>
              <td class="table-cell">
                <StatusBadge status={rev.status} />
              </td>
              <td class="table-cell text-text-secondary">{rev.notes || '-'}</td>
              {#if canManage}
                <td class="table-cell text-right">
                  <button
                    onclick={() => startEdit(rev)}
                    class="mr-2 rounded px-2 py-1 text-2xs text-text-secondary hover:bg-surface-2"
                  >
                    Edit
                  </button>
                  <button
                    onclick={() => promptDelete(rev.id)}
                    class="rounded px-2 py-1 text-2xs text-error hover:bg-error-muted"
                  >
                    Delete
                  </button>
                </td>
              {/if}
            </tr>
          {/each}
        </tbody>
      </table>
    </div>
  {:else}
    <div class="table-empty">
      No board revisions yet
    </div>
  {/if}

  <ConfirmDeleteDialog
    open={!!deleteTarget}
    entityType="board revision"
    entityName={deleteTarget?.name || ''}
    onConfirm={() => { handleDelete(deleteTarget!.id); deleteTarget = null; }}
    onCancel={() => (deleteTarget = null)}
  />
</div>
