// apps/frontend/concord-app/src/app/components/system/namespace-selector.tsx
import { useEffect, useState } from 'react';
import { api } from '../../api';
import { type ApiResponse } from '../../types';
import { Select } from '../ui/select';
import { Namespace } from '../../types/models';

interface NamespaceSelectorProps {
  value: string;
  onChange: (ns: string) => void;
}

export function NamespaceSelector({ value, onChange }: NamespaceSelectorProps) {
  const [namespaces, setNamespaces] = useState<Namespace[]>([]);

  useEffect(() => {
    api<ApiResponse<Namespace[]>>('/v2/system/namespaces')
      .then((res) => setNamespaces(res.data))
      .catch(() => {});
  }, []);

  return (
    <Select
      compact
      value={value}
      onChange={(e) => onChange(e.target.value)}
      aria-label="Select namespace"
    >
      <option value="">All namespaces</option>
      {namespaces.map((ns) => (
        <option key={ns.name} value={ns.name}>
          {ns.name}
        </option>
      ))}
    </Select>
  );
}

// apps/frontend/concord-app-svelte/src/lib/components/system/namespace-selector.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { api } from '$lib/api';
  import Select from '$lib/components/ui/select.svelte';

  interface Props {
    value: string;
    onchange: (ns: string) => void;
  }

  let { value, onchange }: Props = $props();

  let namespaces = $state<string[]>([]);
  let loading = $state(true);

  onMount(async () => {
    try {
      const res = await api.get<{ data: { name: string }[] }>('/v2/system/namespaces');
      if (res?.data) {
        namespaces = res.data.map((n: { name: string }) => n.name);
      }
    } catch {
      // Silently fail, just show all namespaces option
    } finally {
      loading = false;
    }
  });

  function handleChange(e: Event) {
    // The Select component sets value via bind, read it after change
    onchange(String(value));
  }
</script>

<Select
  bind:value={value}
  onchange={handleChange}
  disabled={loading}
  placeholder="All namespaces"
  options={namespaces.map(ns => ({ value: ns, label: ns }))}
  compact
/>
