// apps/frontend/concord-app/src/app/components/system/yaml-viewer.tsx
import { useState, type ReactNode } from 'react';
import { Copy, Check } from 'lucide-react';

interface YamlViewerProps {
  yaml: string;
}

function highlightValue(val: string, keyIndex: number): ReactNode {
  const trimmed = val.trim();
  if (!trimmed) return val;

  if (/^["'].*["']$/.test(trimmed)) {
    return <>{' '}<span key={`v-${keyIndex}`} className="text-success">{trimmed}</span></>;
  }
  if (/^(true|false)$/i.test(trimmed)) {
    return <>{' '}<span key={`v-${keyIndex}`} className="text-warning">{trimmed}</span></>;
  }
  if (/^\d+(\.\d+)?$/.test(trimmed)) {
    return <>{' '}<span key={`v-${keyIndex}`} className="text-info">{trimmed}</span></>;
  }
  if (trimmed === 'null' || trimmed === '~') {
    return <>{' '}<span key={`v-${keyIndex}`} className="text-text-tertiary">{trimmed}</span></>;
  }

  return <>{' '}{trimmed}</>;
}

function highlightLine(line: string, lineIndex: number): ReactNode {
  // Comment lines
  if (line.trimStart().startsWith('#')) {
    return <span className="text-text-tertiary">{line}</span>;
  }

  // Key-value lines: indent + key + colon + value
  const kvMatch = line.match(/^(\s*)([\w.-]+)(:)(.*)$/);
  if (kvMatch) {
    const [, indent, key, colon, val] = kvMatch;
    return (
      <>
        {indent}
        <span className="text-accent">{key}</span>
        {colon}
        {highlightValue(val, lineIndex)}
      </>
    );
  }

  // List item lines: indent + dash + value
  const listMatch = line.match(/^(\s*)(- )(.*)$/);
  if (listMatch) {
    const [, indent, dash, val] = listMatch;
    return (
      <>
        {indent}
        <span className="text-warning">{dash}</span>
        {highlightValue(val, lineIndex)}
      </>
    );
  }

  return line;
}

export function YamlViewer({ yaml }: YamlViewerProps) {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(yaml);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const lines = yaml.split('\n');

  return (
    <div className="relative">
      <button
        onClick={handleCopy}
        aria-label={copied ? 'Copied' : 'Copy to clipboard'}
        className="absolute right-3 top-3 flex items-center gap-1 rounded bg-surface-2 px-2 py-1 text-xs text-text-tertiary transition-colors hover:text-text-primary"
      >
        {copied ? <Check size={12} /> : <Copy size={12} />}
        {copied ? 'Copied' : 'Copy'}
      </button>
      <pre className="overflow-auto rounded-lg border border-border bg-surface-1 p-4 font-mono text-xs leading-5 text-text-secondary">
        {/* key={i} is intentional: static rendered output with no stable ID per line */}
        {lines.map((line, i) => (
          <div key={i} className="hover:bg-surface-2/50">
            {highlightLine(line, i)}
          </div>
        ))}
      </pre>
    </div>
  );
}

// concord/apps/frontend/app/src/lib/components/system/yaml-viewer.svelte
<script lang="ts">
  import { Copy, Check } from 'lucide-svelte';

  interface Props {
    yaml: string;
  }

  let { yaml }: Props = $props();

  let copied = $state(false);

  async function copyToClipboard() {
    await navigator.clipboard.writeText(yaml);
    copied = true;
    setTimeout(() => copied = false, 2000);
  }

  function highlightLine(line: string): { text: string; class: string }[] {
    const parts: { text: string; class: string }[] = [];

    // Comment
    if (line.trim().startsWith('#')) {
      return [{ text: line, class: 'text-text-tertiary' }];
    }

    // Key: value
    const keyMatch = line.match(/^(\s*)([^:\s][^:]*):(.*)$/);
    if (keyMatch) {
      const [, indent, key, value] = keyMatch;
      parts.push({ text: indent, class: '' });
      parts.push({ text: key, class: 'text-accent' });
      parts.push({ text: ':', class: 'text-text-tertiary' });

      const trimmedValue = value.trim();
      if (trimmedValue) {
        parts.push({ text: ' ', class: '' });
        // Determine value type color
        if (trimmedValue === 'true' || trimmedValue === 'false') {
          parts.push({ text: trimmedValue, class: 'text-warning' });
        } else if (trimmedValue === 'null' || trimmedValue === '~') {
          parts.push({ text: trimmedValue, class: 'text-text-tertiary' });
        } else if (/^-?\d+(\.\d+)?$/.test(trimmedValue)) {
          parts.push({ text: trimmedValue, class: 'text-info' });
        } else if (trimmedValue.startsWith('"') || trimmedValue.startsWith("'")) {
          parts.push({ text: trimmedValue, class: 'text-success' });
        } else {
          parts.push({ text: trimmedValue, class: 'text-success' });
        }
      }
      return parts;
    }

    // List item
    if (line.trim().startsWith('-')) {
      const dashMatch = line.match(/^(\s*)(-)(.*)$/);
      if (dashMatch) {
        const [, indent, dash, rest] = dashMatch;
        parts.push({ text: indent, class: '' });
        parts.push({ text: dash, class: 'text-warning' });
        parts.push({ text: rest, class: 'text-text-primary' });
        return parts;
      }
    }

    return [{ text: line, class: 'text-text-primary' }];
  }

  const lines = $derived(yaml.split('\n'));
</script>

<div class="relative rounded-lg bg-surface-0 border border-border overflow-hidden">
  <button
    onclick={copyToClipboard}
    class="absolute top-2 right-2 p-1.5 rounded bg-surface-2 hover:bg-surface-2/80 text-text-secondary"
    aria-label="Copy YAML"
  >
    {#if copied}
      <Check class="w-4 h-4 text-success" />
    {:else}
      <Copy class="w-4 h-4" />
    {/if}
  </button>

  <pre class="p-3 overflow-x-auto text-xs font-mono leading-relaxed max-h-96 overflow-y-auto">{#each lines as line, i}<span class="inline-block w-full hover:bg-surface-2/50">{#each highlightLine(line) as part}<span class={part.class}>{part.text}</span>{/each}</span>
{/each}</pre>
</div>
