// apps/frontend/concord-app/src/app/pages/products/firmware-build-upload.tsx
import { useCallback, useState } from 'react';
import { Upload, X, Check } from 'lucide-react';
import { apiUpload } from '../../api';
import { Select } from '../../components/ui/select';
import { ErrorAlert } from '../../components/ui/error-alert';
import { BoardRevision } from '../../types/models';

export function FirmwareBuildUpload({
  productId,
  applicationId,
  boardRevisions,
  onClose,
  onSuccess,
}: {
  productId: string;
  applicationId: string;
  boardRevisions: BoardRevision[];
  onClose: () => void;
  onSuccess: () => void;
}) {
  const [error, setError] = useState<string | null>(null);
  const [uploading, setUploading] = useState(false);
  const [file, setFile] = useState<File | null>(null);
  const [dragOver, setDragOver] = useState(false);

  const [version, setVersion] = useState('');
  const [majorVersion, setMajorVersion] = useState('0');
  const [minorVersion, setMinorVersion] = useState('0');
  const [buildNumber, setBuildNumber] = useState('0');
  const [boardRevisionId, setBoardRevisionId] = useState('');
  const [bootloaderId, setBootloaderId] = useState('');
  const [isManufacturing, setIsManufacturing] = useState(false);
  const [status, setStatus] = useState('DRAFT');
  const [notes, setNotes] = useState('');

  const handleDrop = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setDragOver(false);
    const dropped = e.dataTransfer.files[0];
    if (dropped) setFile(dropped);
  }, []);

  const handleDragOver = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setDragOver(true);
  }, []);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!file) {
      setError('Please select a file');
      return;
    }
    setError(null);
    setUploading(true);

    try {
      const formData = new FormData();
      formData.append('file', file);
      formData.append('applicationId', applicationId);
      formData.append('version', version);
      formData.append('majorVersion', majorVersion);
      formData.append('minorVersion', minorVersion);
      formData.append('buildNumber', buildNumber);
      if (boardRevisionId) formData.append('boardRevisionId', boardRevisionId);
      if (bootloaderId) formData.append('bootloaderId', bootloaderId);
      formData.append('isManufacturing', String(isManufacturing));
      formData.append('status', status);
      if (notes) formData.append('notes', notes);

      await apiUpload(`/v2/products/${productId}/firmware-builds/upload`, formData);
      onSuccess();
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : 'Failed to upload firmware build');
    } finally {
      setUploading(false);
    }
  };

  return (
    <div className="mb-4 rounded-lg border border-border bg-surface-0 p-4">
      <div className="mb-3 flex items-center justify-between">
        <span className="text-2xs font-medium text-text-secondary">Upload firmware build</span>
        <button onClick={onClose} className="rounded p-1 text-text-tertiary hover:bg-surface-2 hover:text-text-primary">
          <X size={14} />
        </button>
      </div>

      <ErrorAlert message={error} />

      <form onSubmit={handleSubmit}>
        {/* File drop zone */}
        <div
          onDrop={handleDrop}
          onDragOver={handleDragOver}
          onDragLeave={() => setDragOver(false)}
          className={[
            'mb-3 flex flex-col items-center justify-center rounded-lg border-2 border-dashed p-6 transition-colors',
            dragOver ? 'border-accent bg-accent/5' : 'border-border',
            file ? 'bg-success-muted/10' : '',
          ].join(' ')}
        >
          <Upload size={20} className="mb-2 text-text-tertiary" />
          {file ? (
            <div className="text-center">
              <span className="text-sm font-medium text-text-primary">{file.name}</span>
              <span className="ml-2 text-2xs text-text-tertiary">
                ({(file.size / 1024).toFixed(1)} KB)
              </span>
              <button
                type="button"
                onClick={() => setFile(null)}
                className="ml-2 text-2xs text-error hover:underline"
              >
                Remove
              </button>
            </div>
          ) : (
            <div className="text-center">
              <label className="cursor-pointer text-sm text-accent hover:underline">
                Choose file
                <input
                  type="file"
                  className="hidden"
                  accept=".zip,.hex,.ckbin,.bin"
                  onChange={(e) => setFile(e.target.files?.[0] || null)}
                />
              </label>
              <span className="text-sm text-text-tertiary"> or drag and drop</span>
              <div className="mt-1 text-2xs text-text-tertiary">ZIP, HEX, CKBIN, or BIN files</div>
            </div>
          )}
        </div>

        {/* Metadata fields */}
        <div className="mb-3 grid grid-cols-4 gap-3">
          <div>
            <label className="mb-1 block text-2xs font-medium text-text-tertiary">Version</label>
            <input
              type="text"
              required
              value={version}
              onChange={(e) => setVersion(e.target.value)}
              placeholder="1.0.0"
              className="w-full rounded-lg border border-border bg-surface-0 px-3 py-2 text-sm text-text-primary placeholder:text-text-tertiary focus:border-accent focus:outline-none"
            />
          </div>
          <div>
            <label className="mb-1 block text-2xs font-medium text-text-tertiary">Major</label>
            <input
              type="number"
              value={majorVersion}
              onChange={(e) => setMajorVersion(e.target.value)}
              className="w-full rounded-lg border border-border bg-surface-0 px-3 py-2 text-sm text-text-primary focus:border-accent focus:outline-none"
            />
          </div>
          <div>
            <label className="mb-1 block text-2xs font-medium text-text-tertiary">Minor</label>
            <input
              type="number"
              value={minorVersion}
              onChange={(e) => setMinorVersion(e.target.value)}
              className="w-full rounded-lg border border-border bg-surface-0 px-3 py-2 text-sm text-text-primary focus:border-accent focus:outline-none"
            />
          </div>
          <div>
            <label className="mb-1 block text-2xs font-medium text-text-tertiary">Build #</label>
            <input
              type="number"
              value={buildNumber}
              onChange={(e) => setBuildNumber(e.target.value)}
              className="w-full rounded-lg border border-border bg-surface-0 px-3 py-2 text-sm text-text-primary focus:border-accent focus:outline-none"
            />
          </div>
        </div>

        <div className="mb-3 grid grid-cols-3 gap-3">
          <div>
            <label className="mb-1 block text-2xs font-medium text-text-tertiary">Board Revision</label>
            <Select
              value={boardRevisionId}
              onChange={(e) => setBoardRevisionId(e.target.value)}
            >
              <option value="">None</option>
              {boardRevisions.map((r) => (
                <option key={r.id} value={r.id}>
                  {r.version}{r.chipsets.length > 0 ? ` (${r.chipsets.join(', ')})` : ''}
                </option>
              ))}
            </Select>
          </div>
          <div>
            <label className="mb-1 block text-2xs font-medium text-text-tertiary">Bootloader ID</label>
            <input
              type="text"
              value={bootloaderId}
              onChange={(e) => setBootloaderId(e.target.value)}
              placeholder="Optional"
              className="w-full rounded-lg border border-border bg-surface-0 px-3 py-2 text-sm text-text-primary placeholder:text-text-tertiary focus:border-accent focus:outline-none"
            />
          </div>
          <div>
            <label className="mb-1 block text-2xs font-medium text-text-tertiary">Status</label>
            <Select
              value={status}
              onChange={(e) => setStatus(e.target.value)}
            >
              <option value="DRAFT">Draft</option>
              <option value="RELEASED">Released</option>
              <option value="DEPRECATED">Deprecated</option>
            </Select>
          </div>
        </div>

        <div className="mb-3 flex items-center gap-4">
          <label className="flex items-center gap-2 text-sm text-text-primary">
            <input
              type="checkbox"
              checked={isManufacturing}
              onChange={(e) => setIsManufacturing(e.target.checked)}
              className="rounded border-border"
            />
            Manufacturing build
          </label>
        </div>

        <div className="mb-3">
          <label className="mb-1 block text-2xs font-medium text-text-tertiary">Notes</label>
          <input
            type="text"
            value={notes}
            onChange={(e) => setNotes(e.target.value)}
            placeholder="Optional notes"
            className="w-full rounded-lg border border-border bg-surface-0 px-3 py-2 text-sm text-text-primary placeholder:text-text-tertiary focus:border-accent focus:outline-none"
          />
        </div>

        <div className="flex gap-2">
          <button
            type="submit"
            disabled={uploading || !file}
            className="flex items-center gap-1.5 rounded-lg bg-accent px-3 py-1.5 text-2xs font-medium text-white hover:bg-accent-hover disabled:opacity-50"
          >
            <Check size={12} />
            {uploading ? 'Uploading...' : 'Upload'}
          </button>
          <button
            type="button"
            onClick={onClose}
            className="rounded-lg px-3 py-1.5 text-2xs font-medium text-text-secondary hover:bg-surface-2"
          >
            Cancel
          </button>
        </div>
      </form>
    </div>
  );
}

// apps/frontend/concord-app-svelte/src/lib/components/products/firmware-build-upload.svelte
<script lang="ts">
  import { Upload, Check, X } from 'lucide-svelte';
  import { apiUpload } from '$lib/api';
  import Select from '$lib/components/ui/select.svelte';
  import ErrorAlert from '$lib/components/ui/error-alert.svelte';
  import type { BoardRevision } from '$lib/types/models';

  interface Props {
    productId: string;
    applicationId: string;
    boardRevisions: BoardRevision[];
    onSuccess: () => void;
    onCancel: () => void;
  }

  let { productId, applicationId, boardRevisions, onSuccess, onCancel }: Props = $props();

  let error = $state<string | null>(null);
  let dragOver = $state(false);
  let uploading = $state(false);
  let selectedFile = $state<File | null>(null);

  let formVersion = $state('');
  let formMajor = $state(0);
  let formMinor = $state(0);
  let formBuild = $state(0);
  let formBoardRevisionId = $state('');
  let formBootloaderId = $state('');
  let formIsManufacturing = $state(false);
  let formStatus = $state('ACTIVE');
  let formNotes = $state('');

  function handleDrop(e: DragEvent) {
    e.preventDefault();
    dragOver = false;
    const file = e.dataTransfer?.files[0];
    if (file) selectedFile = file;
  }

  function handleFileChange(e: Event) {
    const input = e.target as HTMLInputElement;
    const file = input.files?.[0];
    if (file) selectedFile = file;
    input.value = '';
  }

  async function handleSubmit(e: Event) {
    e.preventDefault();
    if (!selectedFile) {
      error = 'Please select a file to upload';
      return;
    }

    error = null;
    uploading = true;

    const formData = new FormData();
    formData.append('file', selectedFile);
    formData.append('version', formVersion);
    formData.append('majorVersion', String(formMajor));
    formData.append('minorVersion', String(formMinor));
    formData.append('buildNumber', String(formBuild));
    formData.append('applicationId', applicationId);
    if (formBoardRevisionId) formData.append('boardRevisionId', formBoardRevisionId);
    if (formBootloaderId) formData.append('bootloaderId', formBootloaderId);
    formData.append('isManufacturing', String(formIsManufacturing));
    formData.append('status', formStatus);
    if (formNotes) formData.append('notes', formNotes);

    try {
      await apiUpload(`/v2/products/${productId}/firmware-builds`, formData);
      onSuccess();
    } catch (err) {
      error = err instanceof Error ? err.message : 'Failed to upload build';
    } finally {
      uploading = false;
    }
  }
</script>

<div class="rounded-lg border border-border bg-surface-0 p-3">
  <ErrorAlert message={error} />

  <form onsubmit={handleSubmit}>
    <!-- File drop zone -->
    <div
      role="button"
      tabindex="0"
      ondragover={(e) => { e.preventDefault(); dragOver = true; }}
      ondragleave={() => (dragOver = false)}
      ondrop={handleDrop}
      class={[
        'mb-3 flex flex-col items-center justify-center rounded-lg border-2 border-dashed p-4 transition-colors',
        dragOver ? 'border-accent bg-accent-muted' : 'border-border bg-surface-1 hover:border-text-tertiary'
      ].join(' ')}
    >
      <label class="flex cursor-pointer flex-col items-center gap-2">
        <input
          type="file"
          onchange={handleFileChange}
          class="hidden"
        />
        <Upload size={20} class="text-text-tertiary" strokeWidth={1.5} />
        {#if selectedFile}
          <span class="text-xs font-medium text-text-primary">{selectedFile.name}</span>
        {:else}
          <span class="text-2xs text-text-tertiary">Drop firmware file or click to select</span>
        {/if}
      </label>
    </div>

    <div class="grid grid-cols-2 gap-3 sm:grid-cols-4">
      <label>
        <span class="mb-1 block text-2xs font-medium text-text-tertiary">Version</span>
        <input
          type="text"
          required
          bind:value={formVersion}
          placeholder="e.g. 1.0.0"
          class="w-full rounded-lg border border-border bg-surface-1 px-3 py-2 text-sm text-text-primary placeholder:text-text-tertiary focus:border-accent focus:outline-none"
        />
      </label>
      <div class="grid grid-cols-3 gap-1">
        <label>
          <span class="mb-1 block text-2xs font-medium text-text-tertiary">Major</span>
          <input
            type="number"
            min="0"
            bind:value={formMajor}
            class="w-full rounded-lg border border-border bg-surface-1 px-2 py-2 text-sm text-text-primary focus:border-accent focus:outline-none"
          />
        </label>
        <label>
          <span class="mb-1 block text-2xs font-medium text-text-tertiary">Minor</span>
          <input
            type="number"
            min="0"
            bind:value={formMinor}
            class="w-full rounded-lg border border-border bg-surface-1 px-2 py-2 text-sm text-text-primary focus:border-accent focus:outline-none"
          />
        </label>
        <label>
          <span class="mb-1 block text-2xs font-medium text-text-tertiary">Build</span>
          <input
            type="number"
            min="0"
            bind:value={formBuild}
            class="w-full rounded-lg border border-border bg-surface-1 px-2 py-2 text-sm text-text-primary focus:border-accent focus:outline-none"
          />
        </label>
      </div>
      <Select
        bind:value={formBoardRevisionId}
        label="Board Revision"
        placeholder="None"
        options={boardRevisions.map(rev => ({ value: rev.id, label: rev.version }))}
      />
      <Select
        bind:value={formStatus}
        label="Status"
        options={[
          { value: 'ACTIVE', label: 'Active' },
          { value: 'DEPRECATED', label: 'Deprecated' },
          { value: 'EOL', label: 'End of Life' },
        ]}
      />
    </div>

    <div class="mt-3 grid grid-cols-2 gap-3">
      <label>
        <span class="mb-1 block text-2xs font-medium text-text-tertiary">Bootloader ID (optional)</span>
        <input
          type="text"
          bind:value={formBootloaderId}
          placeholder="e.g. BL_1.0"
          class="w-full rounded-lg border border-border bg-surface-1 px-3 py-2 text-sm text-text-primary placeholder:text-text-tertiary focus:border-accent focus:outline-none"
        />
      </label>
      <label>
        <span class="mb-1 block text-2xs font-medium text-text-tertiary">Notes</span>
        <input
          type="text"
          bind:value={formNotes}
          placeholder="Optional"
          class="w-full rounded-lg border border-border bg-surface-1 px-3 py-2 text-sm text-text-primary placeholder:text-text-tertiary focus:border-accent focus:outline-none"
        />
      </label>
    </div>

    <div class="mt-3">
      <label class="flex items-center gap-2 text-sm text-text-primary">
        <input
          type="checkbox"
          bind:checked={formIsManufacturing}
          class="rounded border-border"
        />
        Manufacturing build
      </label>
    </div>

    <div class="mt-4 flex gap-2">
      <button
        type="submit"
        disabled={uploading || !selectedFile}
        class="flex items-center gap-1.5 rounded-lg bg-accent px-3 py-1.5 text-xs font-medium text-white hover:bg-accent-hover disabled:opacity-50"
      >
        <Check size={16} />
        {uploading ? 'Uploading...' : 'Upload'}
      </button>
      <button
        type="button"
        onclick={onCancel}
        class="flex items-center gap-1 rounded-lg px-3 py-1.5 text-xs font-medium text-text-secondary hover:bg-surface-2"
      >
        <X size={16} />
        Cancel
      </button>
    </div>
  </form>
</div>
